//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Area.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Area"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Telephone"/&gt;
 *     &lt;enumeration value="Internet"/&gt;
 *     &lt;enumeration value="TV"/&gt;
 *     &lt;enumeration value="Sales"/&gt;
 *     &lt;enumeration value="Status"/&gt;
 *     &lt;enumeration value="Invoice"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Area")
@XmlEnum
public enum Area {

    @XmlEnumValue("Telephone")
    TELEPHONE("Telephone"),
    @XmlEnumValue("Internet")
    INTERNET("Internet"),
    TV("TV"),
    @XmlEnumValue("Sales")
    SALES("Sales"),
    @XmlEnumValue("Status")
    STATUS("Status"),
    @XmlEnumValue("Invoice")
    INVOICE("Invoice"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    Area(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Area fromValue(String v) {
        for (Area c: Area.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
