//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CallBarring complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallBarring"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InternationalNumbers" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="MobileNumbers" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ServiceNumbers" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ServiceNumberBarring"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallBarring", propOrder = {
    "internationalNumbers",
    "mobileNumbers",
    "serviceNumbers"
})
public class CallBarring {

    @XmlElement(name = "InternationalNumbers")
    protected boolean internationalNumbers;
    @XmlElement(name = "MobileNumbers")
    protected boolean mobileNumbers;
    @XmlElement(name = "ServiceNumbers", required = true)
    protected String serviceNumbers;

    /**
     * Gets the value of the internationalNumbers property.
     * 
     */
    public boolean isInternationalNumbers() {
        return internationalNumbers;
    }

    /**
     * Sets the value of the internationalNumbers property.
     * 
     */
    public void setInternationalNumbers(boolean value) {
        this.internationalNumbers = value;
    }

    /**
     * Gets the value of the mobileNumbers property.
     * 
     */
    public boolean isMobileNumbers() {
        return mobileNumbers;
    }

    /**
     * Sets the value of the mobileNumbers property.
     * 
     */
    public void setMobileNumbers(boolean value) {
        this.mobileNumbers = value;
    }

    /**
     * Gets the value of the serviceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceNumbers() {
        return serviceNumbers;
    }

    /**
     * Sets the value of the serviceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceNumbers(String value) {
        this.serviceNumbers = value;
    }

}
