//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CheckSetPhoneDirectoryEntryResponseDelivery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckSetPhoneDirectoryEntryResponseDelivery"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="PrintName" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}printnameType"/&gt;
 *         &lt;element name="ErrorBlock" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NIDErrorBlockType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckSetPhoneDirectoryEntryResponseDelivery", propOrder = {
    "printName",
    "errorBlock"
})
public class CheckSetPhoneDirectoryEntryResponseDelivery {

    @XmlElement(name = "PrintName")
    protected String printName;
    @XmlElement(name = "ErrorBlock")
    protected NIDErrorBlockType errorBlock;

    /**
     * Gets the value of the printName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintName() {
        return printName;
    }

    /**
     * Sets the value of the printName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintName(String value) {
        this.printName = value;
    }

    /**
     * Gets the value of the errorBlock property.
     * 
     * @return
     *     possible object is
     *     {@link NIDErrorBlockType }
     *     
     */
    public NIDErrorBlockType getErrorBlock() {
        return errorBlock;
    }

    /**
     * Sets the value of the errorBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link NIDErrorBlockType }
     *     
     */
    public void setErrorBlock(NIDErrorBlockType value) {
        this.errorBlock = value;
    }

}
