//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CommercialProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommercialProduct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TechnicalName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PresentationName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}CommercialProductType"/&gt;
 *         &lt;element name="ProductAction" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ProductAction"/&gt;
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RelatedProductId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PresentationSequence" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Price" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price"/&gt;
 *         &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ContractTerm" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ContractTermProlongation" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ContractStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Dependencies" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MonthlyAmountCheck" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}MonthlyAmountCheckLOV" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommercialProduct", propOrder = {
    "productId",
    "technicalName",
    "presentationName",
    "productType",
    "productAction",
    "duration",
    "relatedProductId",
    "presentationSequence",
    "price",
    "priceType",
    "contractTerm",
    "contractTermProlongation",
    "contractStartDate",
    "contractEndDate",
    "dependencies",
    "monthlyAmountCheck"
})
public class CommercialProduct {

    @XmlElement(name = "ProductId", required = true)
    protected String productId;
    @XmlElement(name = "TechnicalName", required = true)
    protected String technicalName;
    @XmlElement(name = "PresentationName", required = true)
    protected String presentationName;
    @XmlElement(name = "ProductType", required = true)
    @XmlSchemaType(name = "string")
    protected CommercialProductType productType;
    @XmlElement(name = "ProductAction", required = true)
    @XmlSchemaType(name = "string")
    protected ProductAction productAction;
    @XmlElement(name = "Duration", required = true)
    protected String duration;
    @XmlElement(name = "RelatedProductId", required = true)
    protected String relatedProductId;
    @XmlElement(name = "PresentationSequence", required = true)
    protected String presentationSequence;
    @XmlElement(name = "Price", required = true)
    protected BigDecimal price;
    @XmlElement(name = "PriceType", required = true)
    protected String priceType;
    @XmlElement(name = "ContractTerm")
    protected Integer contractTerm;
    @XmlElement(name = "ContractTermProlongation")
    protected Integer contractTermProlongation;
    @XmlElement(name = "ContractStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractStartDate;
    @XmlElement(name = "ContractEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractEndDate;
    @XmlElement(name = "Dependencies")
    protected String dependencies;
    @XmlElement(name = "MonthlyAmountCheck")
    @XmlSchemaType(name = "string")
    protected MonthlyAmountCheckLOV monthlyAmountCheck;

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the technicalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalName() {
        return technicalName;
    }

    /**
     * Sets the value of the technicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalName(String value) {
        this.technicalName = value;
    }

    /**
     * Gets the value of the presentationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationName() {
        return presentationName;
    }

    /**
     * Sets the value of the presentationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationName(String value) {
        this.presentationName = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialProductType }
     *     
     */
    public CommercialProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialProductType }
     *     
     */
    public void setProductType(CommercialProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productAction property.
     * 
     * @return
     *     possible object is
     *     {@link ProductAction }
     *     
     */
    public ProductAction getProductAction() {
        return productAction;
    }

    /**
     * Sets the value of the productAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductAction }
     *     
     */
    public void setProductAction(ProductAction value) {
        this.productAction = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the relatedProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedProductId() {
        return relatedProductId;
    }

    /**
     * Sets the value of the relatedProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedProductId(String value) {
        this.relatedProductId = value;
    }

    /**
     * Gets the value of the presentationSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationSequence() {
        return presentationSequence;
    }

    /**
     * Sets the value of the presentationSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationSequence(String value) {
        this.presentationSequence = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the priceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * Sets the value of the priceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceType(String value) {
        this.priceType = value;
    }

    /**
     * Gets the value of the contractTerm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContractTerm() {
        return contractTerm;
    }

    /**
     * Sets the value of the contractTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContractTerm(Integer value) {
        this.contractTerm = value;
    }

    /**
     * Gets the value of the contractTermProlongation property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContractTermProlongation() {
        return contractTermProlongation;
    }

    /**
     * Sets the value of the contractTermProlongation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContractTermProlongation(Integer value) {
        this.contractTermProlongation = value;
    }

    /**
     * Gets the value of the contractStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractStartDate() {
        return contractStartDate;
    }

    /**
     * Sets the value of the contractStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractStartDate(XMLGregorianCalendar value) {
        this.contractStartDate = value;
    }

    /**
     * Gets the value of the contractEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractEndDate() {
        return contractEndDate;
    }

    /**
     * Sets the value of the contractEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractEndDate(XMLGregorianCalendar value) {
        this.contractEndDate = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependencies(String value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the monthlyAmountCheck property.
     * 
     * @return
     *     possible object is
     *     {@link MonthlyAmountCheckLOV }
     *     
     */
    public MonthlyAmountCheckLOV getMonthlyAmountCheck() {
        return monthlyAmountCheck;
    }

    /**
     * Sets the value of the monthlyAmountCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthlyAmountCheckLOV }
     *     
     */
    public void setMonthlyAmountCheck(MonthlyAmountCheckLOV value) {
        this.monthlyAmountCheck = value;
    }

}
