//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FiberProximity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FiberProximity"&gt;
 *   &lt;restriction base="{urn:fiber.kpn.com:crm:frontdesk:data:v0}GlassAvailability"&gt;
 *     &lt;enumeration value="FTTH"/&gt;
 *     &lt;enumeration value="FTTC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FiberProximity")
@XmlEnum(GlassAvailability.class)
public enum FiberProximity {

    FTTH,
    FTTC;

    public String value() {
        return name();
    }

    public static FiberProximity fromValue(String v) {
        return valueOf(v);
    }

}
