//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetAvailablePlanDatesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetAvailablePlanDatesResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="PlanDates" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}AvailablePlanDates"/&gt;
 *         &lt;element name="Error" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}GetAvailablePlanDatesError"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAvailablePlanDatesResponse", propOrder = {
    "planDates",
    "error"
})
public class GetAvailablePlanDatesResponse {

    @XmlElement(name = "PlanDates")
    protected AvailablePlanDates planDates;
    @XmlElement(name = "Error")
    @XmlSchemaType(name = "string")
    protected GetAvailablePlanDatesError error;

    /**
     * Gets the value of the planDates property.
     * 
     * @return
     *     possible object is
     *     {@link AvailablePlanDates }
     *     
     */
    public AvailablePlanDates getPlanDates() {
        return planDates;
    }

    /**
     * Sets the value of the planDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailablePlanDates }
     *     
     */
    public void setPlanDates(AvailablePlanDates value) {
        this.planDates = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link GetAvailablePlanDatesError }
     *     
     */
    public GetAvailablePlanDatesError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAvailablePlanDatesError }
     *     
     */
    public void setError(GetAvailablePlanDatesError value) {
        this.error = value;
    }

}
