//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetConfirmableOrderResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetConfirmableOrderResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="ConfirmableOrder" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ConfirmableOrderSpec"/&gt;
 *         &lt;element name="Error" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}GetConfirmableOrderError"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetConfirmableOrderResponse", propOrder = {
    "confirmableOrder",
    "error"
})
public class GetConfirmableOrderResponse {

    @XmlElement(name = "ConfirmableOrder")
    protected ConfirmableOrderSpec confirmableOrder;
    @XmlElement(name = "Error")
    @XmlSchemaType(name = "string")
    protected GetConfirmableOrderError error;

    /**
     * Gets the value of the confirmableOrder property.
     * 
     * @return
     *     possible object is
     *     {@link ConfirmableOrderSpec }
     *     
     */
    public ConfirmableOrderSpec getConfirmableOrder() {
        return confirmableOrder;
    }

    /**
     * Sets the value of the confirmableOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfirmableOrderSpec }
     *     
     */
    public void setConfirmableOrder(ConfirmableOrderSpec value) {
        this.confirmableOrder = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link GetConfirmableOrderError }
     *     
     */
    public GetConfirmableOrderError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetConfirmableOrderError }
     *     
     */
    public void setError(GetConfirmableOrderError value) {
        this.error = value;
    }

}
