//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetFirstPossibleWishdateTelephoneDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetFirstPossibleWishdateTelephoneDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IsNewNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IsWLR" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Telco" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String255"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFirstPossibleWishdateTelephoneDetails", propOrder = {
    "isNewNumber",
    "isWLR",
    "telco"
})
public class GetFirstPossibleWishdateTelephoneDetails {

    @XmlElement(name = "IsNewNumber")
    protected boolean isNewNumber;
    @XmlElement(name = "IsWLR")
    protected boolean isWLR;
    @XmlElement(name = "Telco", required = true)
    protected String telco;

    /**
     * Gets the value of the isNewNumber property.
     * 
     */
    public boolean isIsNewNumber() {
        return isNewNumber;
    }

    /**
     * Sets the value of the isNewNumber property.
     * 
     */
    public void setIsNewNumber(boolean value) {
        this.isNewNumber = value;
    }

    /**
     * Gets the value of the isWLR property.
     * 
     */
    public boolean isIsWLR() {
        return isWLR;
    }

    /**
     * Sets the value of the isWLR property.
     * 
     */
    public void setIsWLR(boolean value) {
        this.isWLR = value;
    }

    /**
     * Gets the value of the telco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelco() {
        return telco;
    }

    /**
     * Sets the value of the telco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelco(String value) {
        this.telco = value;
    }

}
