//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetMailSettingsResponseParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetMailSettingsResponseParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmailName" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String255"/&gt;
 *         &lt;element name="Spamfilter" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Virusscan" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Alias" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Alias" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetMailSettingsResponseParameters", propOrder = {
    "emailName",
    "spamfilter",
    "virusscan",
    "alias"
})
public class GetMailSettingsResponseParameters {

    @XmlElement(name = "EmailName", required = true)
    protected String emailName;
    @XmlElement(name = "Spamfilter")
    protected boolean spamfilter;
    @XmlElement(name = "Virusscan")
    protected boolean virusscan;
    @XmlElement(name = "Alias")
    protected List<Alias> alias;

    /**
     * Gets the value of the emailName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailName() {
        return emailName;
    }

    /**
     * Sets the value of the emailName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailName(String value) {
        this.emailName = value;
    }

    /**
     * Gets the value of the spamfilter property.
     * 
     */
    public boolean isSpamfilter() {
        return spamfilter;
    }

    /**
     * Sets the value of the spamfilter property.
     * 
     */
    public void setSpamfilter(boolean value) {
        this.spamfilter = value;
    }

    /**
     * Gets the value of the virusscan property.
     * 
     */
    public boolean isVirusscan() {
        return virusscan;
    }

    /**
     * Sets the value of the virusscan property.
     * 
     */
    public void setVirusscan(boolean value) {
        this.virusscan = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alias }
     * 
     * 
     */
    public List<Alias> getAlias() {
        if (alias == null) {
            alias = new ArrayList<Alias>();
        }
        return this.alias;
    }

}
