//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetOrderableProductsForAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOrderableProductsForAddress"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FiberProximity" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}FiberProximity"/&gt;
 *         &lt;element name="Address" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}AddressSpec"/&gt;
 *         &lt;element name="Brand" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Brand" minOccurs="0"/&gt;
 *         &lt;element name="OrderMethod" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}OrderMethod"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOrderableProductsForAddress", propOrder = {
    "fiberProximity",
    "address",
    "brand",
    "orderMethod"
})
public class GetOrderableProductsForAddress {

    @XmlElement(name = "FiberProximity", required = true)
    @XmlSchemaType(name = "string")
    protected FiberProximity fiberProximity;
    @XmlElement(name = "Address", required = true)
    protected AddressSpec address;
    @XmlElement(name = "Brand")
    protected String brand;
    @XmlElement(name = "OrderMethod", required = true)
    @XmlSchemaType(name = "string")
    protected OrderMethod orderMethod;

    /**
     * Gets the value of the fiberProximity property.
     * 
     * @return
     *     possible object is
     *     {@link FiberProximity }
     *     
     */
    public FiberProximity getFiberProximity() {
        return fiberProximity;
    }

    /**
     * Sets the value of the fiberProximity property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiberProximity }
     *     
     */
    public void setFiberProximity(FiberProximity value) {
        this.fiberProximity = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressSpec }
     *     
     */
    public AddressSpec getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressSpec }
     *     
     */
    public void setAddress(AddressSpec value) {
        this.address = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the orderMethod property.
     * 
     * @return
     *     possible object is
     *     {@link OrderMethod }
     *     
     */
    public OrderMethod getOrderMethod() {
        return orderMethod;
    }

    /**
     * Sets the value of the orderMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderMethod }
     *     
     */
    public void setOrderMethod(OrderMethod value) {
        this.orderMethod = value;
    }

}
