//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetServicingInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetServicingInfoResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KPNEngineer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="AccessEngineer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PassAccessAppointment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="AccessInstallationType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" minOccurs="0"/&gt;
 *         &lt;element name="orderScenario" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" minOccurs="0"/&gt;
 *         &lt;element name="AdminCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CreateAgentActivity" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" minOccurs="0"/&gt;
 *         &lt;element name="NlType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" minOccurs="0"/&gt;
 *         &lt;element name="FTUType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" minOccurs="0"/&gt;
 *         &lt;element name="TestEnLabel" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Flag" minOccurs="0"/&gt;
 *         &lt;element name="AccessInstallation" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}AccessInstallation" minOccurs="0"/&gt;
 *         &lt;element name="AgentActivityReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ResultCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetServicingInfoResponse", propOrder = {
    "kpnEngineer",
    "accessEngineer",
    "passAccessAppointment",
    "accessInstallationType",
    "orderScenario",
    "adminCheck",
    "createAgentActivity",
    "nlType",
    "ftuType",
    "testEnLabel",
    "accessInstallation",
    "agentActivityReason",
    "resultCode",
    "resultCodeDescription"
})
public class GetServicingInfoResponse {

    @XmlElement(name = "KPNEngineer")
    protected Boolean kpnEngineer;
    @XmlElement(name = "AccessEngineer")
    protected Boolean accessEngineer;
    @XmlElement(name = "PassAccessAppointment")
    protected Boolean passAccessAppointment;
    @XmlElement(name = "AccessInstallationType")
    protected String accessInstallationType;
    protected String orderScenario;
    @XmlElement(name = "AdminCheck")
    protected Boolean adminCheck;
    @XmlElement(name = "CreateAgentActivity")
    protected String createAgentActivity;
    @XmlElement(name = "NlType")
    protected String nlType;
    @XmlElement(name = "FTUType")
    protected String ftuType;
    @XmlElement(name = "TestEnLabel")
    protected String testEnLabel;
    @XmlElement(name = "AccessInstallation")
    @XmlSchemaType(name = "string")
    protected AccessInstallation accessInstallation;
    @XmlElement(name = "AgentActivityReason")
    protected String agentActivityReason;
    @XmlElement(name = "ResultCode")
    protected String resultCode;
    @XmlElement(name = "ResultCodeDescription")
    protected String resultCodeDescription;

    /**
     * Gets the value of the kpnEngineer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKPNEngineer() {
        return kpnEngineer;
    }

    /**
     * Sets the value of the kpnEngineer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKPNEngineer(Boolean value) {
        this.kpnEngineer = value;
    }

    /**
     * Gets the value of the accessEngineer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAccessEngineer() {
        return accessEngineer;
    }

    /**
     * Sets the value of the accessEngineer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccessEngineer(Boolean value) {
        this.accessEngineer = value;
    }

    /**
     * Gets the value of the passAccessAppointment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassAccessAppointment() {
        return passAccessAppointment;
    }

    /**
     * Sets the value of the passAccessAppointment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassAccessAppointment(Boolean value) {
        this.passAccessAppointment = value;
    }

    /**
     * Gets the value of the accessInstallationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessInstallationType() {
        return accessInstallationType;
    }

    /**
     * Sets the value of the accessInstallationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessInstallationType(String value) {
        this.accessInstallationType = value;
    }

    /**
     * Gets the value of the orderScenario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderScenario() {
        return orderScenario;
    }

    /**
     * Sets the value of the orderScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderScenario(String value) {
        this.orderScenario = value;
    }

    /**
     * Gets the value of the adminCheck property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdminCheck() {
        return adminCheck;
    }

    /**
     * Sets the value of the adminCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdminCheck(Boolean value) {
        this.adminCheck = value;
    }

    /**
     * Gets the value of the createAgentActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateAgentActivity() {
        return createAgentActivity;
    }

    /**
     * Sets the value of the createAgentActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateAgentActivity(String value) {
        this.createAgentActivity = value;
    }

    /**
     * Gets the value of the nlType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNlType() {
        return nlType;
    }

    /**
     * Sets the value of the nlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNlType(String value) {
        this.nlType = value;
    }

    /**
     * Gets the value of the ftuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTUType() {
        return ftuType;
    }

    /**
     * Sets the value of the ftuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTUType(String value) {
        this.ftuType = value;
    }

    /**
     * Gets the value of the testEnLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestEnLabel() {
        return testEnLabel;
    }

    /**
     * Sets the value of the testEnLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestEnLabel(String value) {
        this.testEnLabel = value;
    }

    /**
     * Gets the value of the accessInstallation property.
     * 
     * @return
     *     possible object is
     *     {@link AccessInstallation }
     *     
     */
    public AccessInstallation getAccessInstallation() {
        return accessInstallation;
    }

    /**
     * Sets the value of the accessInstallation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessInstallation }
     *     
     */
    public void setAccessInstallation(AccessInstallation value) {
        this.accessInstallation = value;
    }

    /**
     * Gets the value of the agentActivityReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentActivityReason() {
        return agentActivityReason;
    }

    /**
     * Sets the value of the agentActivityReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentActivityReason(String value) {
        this.agentActivityReason = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCodeDescription() {
        return resultCodeDescription;
    }

    /**
     * Sets the value of the resultCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCodeDescription(String value) {
        this.resultCodeDescription = value;
    }

}
