//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MailSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MailSummary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MovedItems" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="FailedItems" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SourceMailboxDeleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MailSummary", propOrder = {
    "movedItems",
    "failedItems",
    "sourceMailboxDeleted"
})
public class MailSummary {

    @XmlElement(name = "MovedItems")
    protected int movedItems;
    @XmlElement(name = "FailedItems")
    protected int failedItems;
    @XmlElement(name = "SourceMailboxDeleted")
    protected boolean sourceMailboxDeleted;

    /**
     * Gets the value of the movedItems property.
     * 
     */
    public int getMovedItems() {
        return movedItems;
    }

    /**
     * Sets the value of the movedItems property.
     * 
     */
    public void setMovedItems(int value) {
        this.movedItems = value;
    }

    /**
     * Gets the value of the failedItems property.
     * 
     */
    public int getFailedItems() {
        return failedItems;
    }

    /**
     * Sets the value of the failedItems property.
     * 
     */
    public void setFailedItems(int value) {
        this.failedItems = value;
    }

    /**
     * Gets the value of the sourceMailboxDeleted property.
     * 
     */
    public boolean isSourceMailboxDeleted() {
        return sourceMailboxDeleted;
    }

    /**
     * Sets the value of the sourceMailboxDeleted property.
     * 
     */
    public void setSourceMailboxDeleted(boolean value) {
        this.sourceMailboxDeleted = value;
    }

}
