//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MoveOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MoveOrder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TopLevelOrder"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}CustomerNumber"/&gt;
 *         &lt;element name="Brand" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Brand2" minOccurs="0"/&gt;
 *         &lt;element name="NewAddress" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Address"/&gt;
 *         &lt;element name="ShippingAddress" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Address" minOccurs="0"/&gt;
 *         &lt;element name="AlternateShippingAddressFlag" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}AlternateShippingAddressFlag" minOccurs="0"/&gt;
 *         &lt;element name="NewProductLine" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ProductLine" minOccurs="0"/&gt;
 *         &lt;element name="ContractInfo" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ContractInfo" maxOccurs="4" minOccurs="0"/&gt;
 *         &lt;element name="FiberProximityOnNewAddress" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}FiberProximity" minOccurs="0"/&gt;
 *         &lt;element name="PrequalInfo" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}PrequalInfo"/&gt;
 *         &lt;element name="WishDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="DiscontinueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PhoneNumberInfo" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}PhoneNumberInfo" maxOccurs="8" minOccurs="0"/&gt;
 *         &lt;element name="SmartCardNumbers" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}SmartCardNumbers" minOccurs="0"/&gt;
 *         &lt;element name="VdslPortingApproval" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CommercialProducts" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}CommercialProducts"/&gt;
 *         &lt;element name="FTUType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CarrierType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentCarrierType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Upload" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Download" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RGswap" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}RGSwap" minOccurs="0"/&gt;
 *         &lt;element name="NTswap" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NTSwap" minOccurs="0"/&gt;
 *         &lt;element name="EthernetSwitch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ITVResourceProfile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LineSharing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TestLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrderScenario" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}OrderScenario" minOccurs="0"/&gt;
 *         &lt;element name="AgentActivityReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AccessInstallation" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}AccessInstallation" minOccurs="0"/&gt;
 *         &lt;element name="NlType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NlType"/&gt;
 *         &lt;element name="EngineerAppointmentID" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String50" minOccurs="0"/&gt;
 *         &lt;element name="TimeSlot" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TimeSlot" minOccurs="0"/&gt;
 *         &lt;element name="EnableEngineerPlanning" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="DisconnectInfo" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}DisconnectInfo" maxOccurs="6" minOccurs="0"/&gt;
 *         &lt;element name="RGMode" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}RGMode" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationMedium" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String30" minOccurs="0"/&gt;
 *         &lt;element name="AlertId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProvisionedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PublicOrderNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PrequalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MoveOrder", propOrder = {
    "customerNumber",
    "brand",
    "newAddress",
    "shippingAddress",
    "alternateShippingAddressFlag",
    "newProductLine",
    "contractInfo",
    "fiberProximityOnNewAddress",
    "prequalInfo",
    "wishDate",
    "discontinueDate",
    "phoneNumberInfo",
    "smartCardNumbers",
    "vdslPortingApproval",
    "commercialProducts",
    "ftuType",
    "carrierType",
    "currentCarrierType",
    "upload",
    "download",
    "rGswap",
    "nTswap",
    "ethernetSwitch",
    "itvResourceProfile",
    "lineSharing",
    "testLabel",
    "orderScenario",
    "agentActivityReason",
    "accessInstallation",
    "nlType",
    "engineerAppointmentID",
    "timeSlot",
    "enableEngineerPlanning",
    "disconnectInfo",
    "rgMode",
    "communicationMedium",
    "alertId",
    "provisionedBy",
    "publicOrderNr",
    "prequalID"
})
public class MoveOrder
    extends TopLevelOrder
{

    @XmlElement(name = "CustomerNumber", required = true)
    protected String customerNumber;
    @XmlElement(name = "Brand")
    @XmlSchemaType(name = "string")
    protected Brand2 brand;
    @XmlElement(name = "NewAddress", required = true)
    protected Address newAddress;
    @XmlElement(name = "ShippingAddress")
    protected Address shippingAddress;
    @XmlElement(name = "AlternateShippingAddressFlag")
    @XmlSchemaType(name = "string")
    protected AlternateShippingAddressFlag alternateShippingAddressFlag;
    @XmlElement(name = "NewProductLine")
    @XmlSchemaType(name = "string")
    protected ProductLine newProductLine;
    @XmlElement(name = "ContractInfo")
    protected List<ContractInfo> contractInfo;
    @XmlElement(name = "FiberProximityOnNewAddress")
    @XmlSchemaType(name = "string")
    protected FiberProximity fiberProximityOnNewAddress;
    @XmlElement(name = "PrequalInfo", required = true)
    protected PrequalInfo prequalInfo;
    @XmlElement(name = "WishDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar wishDate;
    @XmlElement(name = "DiscontinueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar discontinueDate;
    @XmlElement(name = "PhoneNumberInfo")
    protected List<PhoneNumberInfo> phoneNumberInfo;
    @XmlElement(name = "SmartCardNumbers")
    protected SmartCardNumbers smartCardNumbers;
    @XmlElement(name = "VdslPortingApproval")
    protected Boolean vdslPortingApproval;
    @XmlElement(name = "CommercialProducts", required = true)
    protected CommercialProducts commercialProducts;
    @XmlElement(name = "FTUType")
    protected String ftuType;
    @XmlElement(name = "CarrierType")
    protected String carrierType;
    @XmlElement(name = "CurrentCarrierType")
    protected String currentCarrierType;
    @XmlElement(name = "Upload")
    protected String upload;
    @XmlElement(name = "Download")
    protected String download;
    @XmlElement(name = "RGswap")
    @XmlSchemaType(name = "string")
    protected RGSwap rGswap;
    @XmlElement(name = "NTswap")
    @XmlSchemaType(name = "string")
    protected NTSwap nTswap;
    @XmlElement(name = "EthernetSwitch")
    protected String ethernetSwitch;
    @XmlElement(name = "ITVResourceProfile")
    protected String itvResourceProfile;
    @XmlElement(name = "LineSharing")
    protected String lineSharing;
    @XmlElement(name = "TestLabel")
    protected String testLabel;
    @XmlElement(name = "OrderScenario")
    protected String orderScenario;
    @XmlElement(name = "AgentActivityReason")
    protected String agentActivityReason;
    @XmlElement(name = "AccessInstallation")
    @XmlSchemaType(name = "string")
    protected AccessInstallation accessInstallation;
    @XmlElement(name = "NlType", required = true)
    protected String nlType;
    @XmlElement(name = "EngineerAppointmentID")
    protected String engineerAppointmentID;
    @XmlElement(name = "TimeSlot")
    protected TimeSlot timeSlot;
    @XmlElement(name = "EnableEngineerPlanning")
    protected Boolean enableEngineerPlanning;
    @XmlElement(name = "DisconnectInfo")
    protected List<DisconnectInfo> disconnectInfo;
    @XmlElement(name = "RGMode")
    protected String rgMode;
    @XmlElement(name = "CommunicationMedium")
    protected String communicationMedium;
    @XmlElement(name = "AlertId")
    protected String alertId;
    @XmlElement(name = "ProvisionedBy")
    protected String provisionedBy;
    @XmlElement(name = "PublicOrderNr")
    protected String publicOrderNr;
    @XmlElement(name = "PrequalID")
    protected String prequalID;

    /**
     * Gets the value of the customerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Sets the value of the customerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link Brand2 }
     *     
     */
    public Brand2 getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Brand2 }
     *     
     */
    public void setBrand(Brand2 value) {
        this.brand = value;
    }

    /**
     * Gets the value of the newAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getNewAddress() {
        return newAddress;
    }

    /**
     * Sets the value of the newAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setNewAddress(Address value) {
        this.newAddress = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setShippingAddress(Address value) {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the alternateShippingAddressFlag property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateShippingAddressFlag }
     *     
     */
    public AlternateShippingAddressFlag getAlternateShippingAddressFlag() {
        return alternateShippingAddressFlag;
    }

    /**
     * Sets the value of the alternateShippingAddressFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateShippingAddressFlag }
     *     
     */
    public void setAlternateShippingAddressFlag(AlternateShippingAddressFlag value) {
        this.alternateShippingAddressFlag = value;
    }

    /**
     * Gets the value of the newProductLine property.
     * 
     * @return
     *     possible object is
     *     {@link ProductLine }
     *     
     */
    public ProductLine getNewProductLine() {
        return newProductLine;
    }

    /**
     * Sets the value of the newProductLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductLine }
     *     
     */
    public void setNewProductLine(ProductLine value) {
        this.newProductLine = value;
    }

    /**
     * Gets the value of the contractInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContractInfo }
     * 
     * 
     */
    public List<ContractInfo> getContractInfo() {
        if (contractInfo == null) {
            contractInfo = new ArrayList<ContractInfo>();
        }
        return this.contractInfo;
    }

    /**
     * Gets the value of the fiberProximityOnNewAddress property.
     * 
     * @return
     *     possible object is
     *     {@link FiberProximity }
     *     
     */
    public FiberProximity getFiberProximityOnNewAddress() {
        return fiberProximityOnNewAddress;
    }

    /**
     * Sets the value of the fiberProximityOnNewAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiberProximity }
     *     
     */
    public void setFiberProximityOnNewAddress(FiberProximity value) {
        this.fiberProximityOnNewAddress = value;
    }

    /**
     * Gets the value of the prequalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PrequalInfo }
     *     
     */
    public PrequalInfo getPrequalInfo() {
        return prequalInfo;
    }

    /**
     * Sets the value of the prequalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrequalInfo }
     *     
     */
    public void setPrequalInfo(PrequalInfo value) {
        this.prequalInfo = value;
    }

    /**
     * Gets the value of the wishDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWishDate() {
        return wishDate;
    }

    /**
     * Sets the value of the wishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWishDate(XMLGregorianCalendar value) {
        this.wishDate = value;
    }

    /**
     * Gets the value of the discontinueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDiscontinueDate() {
        return discontinueDate;
    }

    /**
     * Sets the value of the discontinueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDiscontinueDate(XMLGregorianCalendar value) {
        this.discontinueDate = value;
    }

    /**
     * Gets the value of the phoneNumberInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneNumberInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneNumberInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneNumberInfo }
     * 
     * 
     */
    public List<PhoneNumberInfo> getPhoneNumberInfo() {
        if (phoneNumberInfo == null) {
            phoneNumberInfo = new ArrayList<PhoneNumberInfo>();
        }
        return this.phoneNumberInfo;
    }

    /**
     * Gets the value of the smartCardNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link SmartCardNumbers }
     *     
     */
    public SmartCardNumbers getSmartCardNumbers() {
        return smartCardNumbers;
    }

    /**
     * Sets the value of the smartCardNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmartCardNumbers }
     *     
     */
    public void setSmartCardNumbers(SmartCardNumbers value) {
        this.smartCardNumbers = value;
    }

    /**
     * Gets the value of the vdslPortingApproval property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVdslPortingApproval() {
        return vdslPortingApproval;
    }

    /**
     * Sets the value of the vdslPortingApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVdslPortingApproval(Boolean value) {
        this.vdslPortingApproval = value;
    }

    /**
     * Gets the value of the commercialProducts property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialProducts }
     *     
     */
    public CommercialProducts getCommercialProducts() {
        return commercialProducts;
    }

    /**
     * Sets the value of the commercialProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialProducts }
     *     
     */
    public void setCommercialProducts(CommercialProducts value) {
        this.commercialProducts = value;
    }

    /**
     * Gets the value of the ftuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTUType() {
        return ftuType;
    }

    /**
     * Sets the value of the ftuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTUType(String value) {
        this.ftuType = value;
    }

    /**
     * Gets the value of the carrierType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierType() {
        return carrierType;
    }

    /**
     * Sets the value of the carrierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierType(String value) {
        this.carrierType = value;
    }

    /**
     * Gets the value of the currentCarrierType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentCarrierType() {
        return currentCarrierType;
    }

    /**
     * Sets the value of the currentCarrierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentCarrierType(String value) {
        this.currentCarrierType = value;
    }

    /**
     * Gets the value of the upload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpload() {
        return upload;
    }

    /**
     * Sets the value of the upload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpload(String value) {
        this.upload = value;
    }

    /**
     * Gets the value of the download property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDownload() {
        return download;
    }

    /**
     * Sets the value of the download property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDownload(String value) {
        this.download = value;
    }

    /**
     * Gets the value of the rGswap property.
     * 
     * @return
     *     possible object is
     *     {@link RGSwap }
     *     
     */
    public RGSwap getRGswap() {
        return rGswap;
    }

    /**
     * Sets the value of the rGswap property.
     * 
     * @param value
     *     allowed object is
     *     {@link RGSwap }
     *     
     */
    public void setRGswap(RGSwap value) {
        this.rGswap = value;
    }

    /**
     * Gets the value of the nTswap property.
     * 
     * @return
     *     possible object is
     *     {@link NTSwap }
     *     
     */
    public NTSwap getNTswap() {
        return nTswap;
    }

    /**
     * Sets the value of the nTswap property.
     * 
     * @param value
     *     allowed object is
     *     {@link NTSwap }
     *     
     */
    public void setNTswap(NTSwap value) {
        this.nTswap = value;
    }

    /**
     * Gets the value of the ethernetSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthernetSwitch() {
        return ethernetSwitch;
    }

    /**
     * Sets the value of the ethernetSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthernetSwitch(String value) {
        this.ethernetSwitch = value;
    }

    /**
     * Gets the value of the itvResourceProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITVResourceProfile() {
        return itvResourceProfile;
    }

    /**
     * Sets the value of the itvResourceProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITVResourceProfile(String value) {
        this.itvResourceProfile = value;
    }

    /**
     * Gets the value of the lineSharing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineSharing() {
        return lineSharing;
    }

    /**
     * Sets the value of the lineSharing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineSharing(String value) {
        this.lineSharing = value;
    }

    /**
     * Gets the value of the testLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestLabel() {
        return testLabel;
    }

    /**
     * Sets the value of the testLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestLabel(String value) {
        this.testLabel = value;
    }

    /**
     * Gets the value of the orderScenario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderScenario() {
        return orderScenario;
    }

    /**
     * Sets the value of the orderScenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderScenario(String value) {
        this.orderScenario = value;
    }

    /**
     * Gets the value of the agentActivityReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentActivityReason() {
        return agentActivityReason;
    }

    /**
     * Sets the value of the agentActivityReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentActivityReason(String value) {
        this.agentActivityReason = value;
    }

    /**
     * Gets the value of the accessInstallation property.
     * 
     * @return
     *     possible object is
     *     {@link AccessInstallation }
     *     
     */
    public AccessInstallation getAccessInstallation() {
        return accessInstallation;
    }

    /**
     * Sets the value of the accessInstallation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessInstallation }
     *     
     */
    public void setAccessInstallation(AccessInstallation value) {
        this.accessInstallation = value;
    }

    /**
     * Gets the value of the nlType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNlType() {
        return nlType;
    }

    /**
     * Sets the value of the nlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNlType(String value) {
        this.nlType = value;
    }

    /**
     * Gets the value of the engineerAppointmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineerAppointmentID() {
        return engineerAppointmentID;
    }

    /**
     * Sets the value of the engineerAppointmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineerAppointmentID(String value) {
        this.engineerAppointmentID = value;
    }

    /**
     * Gets the value of the timeSlot property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSlot }
     *     
     */
    public TimeSlot getTimeSlot() {
        return timeSlot;
    }

    /**
     * Sets the value of the timeSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSlot }
     *     
     */
    public void setTimeSlot(TimeSlot value) {
        this.timeSlot = value;
    }

    /**
     * Gets the value of the enableEngineerPlanning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableEngineerPlanning() {
        return enableEngineerPlanning;
    }

    /**
     * Sets the value of the enableEngineerPlanning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableEngineerPlanning(Boolean value) {
        this.enableEngineerPlanning = value;
    }

    /**
     * Gets the value of the disconnectInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disconnectInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisconnectInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisconnectInfo }
     * 
     * 
     */
    public List<DisconnectInfo> getDisconnectInfo() {
        if (disconnectInfo == null) {
            disconnectInfo = new ArrayList<DisconnectInfo>();
        }
        return this.disconnectInfo;
    }

    /**
     * Gets the value of the rgMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRGMode() {
        return rgMode;
    }

    /**
     * Sets the value of the rgMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRGMode(String value) {
        this.rgMode = value;
    }

    /**
     * Gets the value of the communicationMedium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationMedium() {
        return communicationMedium;
    }

    /**
     * Sets the value of the communicationMedium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationMedium(String value) {
        this.communicationMedium = value;
    }

    /**
     * Gets the value of the alertId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertId() {
        return alertId;
    }

    /**
     * Sets the value of the alertId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertId(String value) {
        this.alertId = value;
    }

    /**
     * Gets the value of the provisionedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisionedBy() {
        return provisionedBy;
    }

    /**
     * Sets the value of the provisionedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisionedBy(String value) {
        this.provisionedBy = value;
    }

    /**
     * Gets the value of the publicOrderNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicOrderNr() {
        return publicOrderNr;
    }

    /**
     * Sets the value of the publicOrderNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicOrderNr(String value) {
        this.publicOrderNr = value;
    }

    /**
     * Gets the value of the prequalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrequalID() {
        return prequalID;
    }

    /**
     * Sets the value of the prequalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrequalID(String value) {
        this.prequalID = value;
    }

}
