//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NIDErrorBlockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NIDErrorBlockType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NIDResultCode" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NIDErrorCode" minOccurs="0"/&gt;
 *         &lt;element name="NIDResultMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NIDErrorBlockType", propOrder = {
    "nidResultCode",
    "nidResultMessage"
})
public class NIDErrorBlockType {

    @XmlElement(name = "NIDResultCode")
    @XmlSchemaType(name = "string")
    protected NIDErrorCode nidResultCode;
    @XmlElement(name = "NIDResultMessage")
    protected String nidResultMessage;

    /**
     * Gets the value of the nidResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link NIDErrorCode }
     *     
     */
    public NIDErrorCode getNIDResultCode() {
        return nidResultCode;
    }

    /**
     * Sets the value of the nidResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NIDErrorCode }
     *     
     */
    public void setNIDResultCode(NIDErrorCode value) {
        this.nidResultCode = value;
    }

    /**
     * Gets the value of the nidResultMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIDResultMessage() {
        return nidResultMessage;
    }

    /**
     * Sets the value of the nidResultMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIDResultMessage(String value) {
        this.nidResultMessage = value;
    }

}
