//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NumberPorting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumberPorting"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PhoneNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TelephoneNumber"/&gt;
 *         &lt;element name="NumberPortingApproval" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="PortingAddress" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Address"/&gt;
 *         &lt;element name="Telco" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String255" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumberPorting", propOrder = {
    "phoneNumber",
    "numberPortingApproval",
    "portingAddress",
    "telco"
})
public class NumberPorting {

    @XmlElement(name = "PhoneNumber", required = true)
    protected String phoneNumber;
    @XmlElement(name = "NumberPortingApproval")
    protected boolean numberPortingApproval;
    @XmlElement(name = "PortingAddress", required = true)
    protected Address portingAddress;
    @XmlElement(name = "Telco")
    protected String telco;

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the numberPortingApproval property.
     * 
     */
    public boolean isNumberPortingApproval() {
        return numberPortingApproval;
    }

    /**
     * Sets the value of the numberPortingApproval property.
     * 
     */
    public void setNumberPortingApproval(boolean value) {
        this.numberPortingApproval = value;
    }

    /**
     * Gets the value of the portingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getPortingAddress() {
        return portingAddress;
    }

    /**
     * Sets the value of the portingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setPortingAddress(Address value) {
        this.portingAddress = value;
    }

    /**
     * Gets the value of the telco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelco() {
        return telco;
    }

    /**
     * Sets the value of the telco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelco(String value) {
        this.telco = value;
    }

}
