//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderlineProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderlineProduct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductCategory" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ProductCategory" minOccurs="0"/&gt;
 *         &lt;element name="ProductModel" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String32" minOccurs="0"/&gt;
 *         &lt;element name="ProductAction" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ProductAction" minOccurs="0"/&gt;
 *         &lt;element name="ProductOneTimeCost" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price" minOccurs="0"/&gt;
 *         &lt;element name="ProductRecurringCost" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price" minOccurs="0"/&gt;
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderlineProduct", propOrder = {
    "productId",
    "productName",
    "productCategory",
    "productModel",
    "productAction",
    "productOneTimeCost",
    "productRecurringCost",
    "quantity"
})
public class OrderlineProduct {

    @XmlElement(name = "ProductId", required = true)
    protected String productId;
    @XmlElement(name = "ProductName", required = true)
    protected String productName;
    @XmlElement(name = "ProductCategory")
    @XmlSchemaType(name = "string")
    protected ProductCategory productCategory;
    @XmlElement(name = "ProductModel")
    protected String productModel;
    @XmlElement(name = "ProductAction")
    @XmlSchemaType(name = "string")
    protected ProductAction productAction;
    @XmlElement(name = "ProductOneTimeCost")
    protected BigDecimal productOneTimeCost;
    @XmlElement(name = "ProductRecurringCost")
    protected BigDecimal productRecurringCost;
    @XmlElement(name = "Quantity")
    protected Integer quantity;

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategory }
     *     
     */
    public ProductCategory getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategory }
     *     
     */
    public void setProductCategory(ProductCategory value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * Sets the value of the productModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductModel(String value) {
        this.productModel = value;
    }

    /**
     * Gets the value of the productAction property.
     * 
     * @return
     *     possible object is
     *     {@link ProductAction }
     *     
     */
    public ProductAction getProductAction() {
        return productAction;
    }

    /**
     * Sets the value of the productAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductAction }
     *     
     */
    public void setProductAction(ProductAction value) {
        this.productAction = value;
    }

    /**
     * Gets the value of the productOneTimeCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductOneTimeCost() {
        return productOneTimeCost;
    }

    /**
     * Sets the value of the productOneTimeCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductOneTimeCost(BigDecimal value) {
        this.productOneTimeCost = value;
    }

    /**
     * Gets the value of the productRecurringCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductRecurringCost() {
        return productRecurringCost;
    }

    /**
     * Sets the value of the productRecurringCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductRecurringCost(BigDecimal value) {
        this.productRecurringCost = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuantity(Integer value) {
        this.quantity = value;
    }

}
