//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Base"/&gt;
 *     &lt;enumeration value="Access"/&gt;
 *     &lt;enumeration value="Proposition"/&gt;
 *     &lt;enumeration value="Change"/&gt;
 *     &lt;enumeration value="Terminate"/&gt;
 *     &lt;enumeration value="Termination"/&gt;
 *     &lt;enumeration value="Move"/&gt;
 *     &lt;enumeration value="MoveAccess"/&gt;
 *     &lt;enumeration value="MovePropositionNew"/&gt;
 *     &lt;enumeration value="MovePropositionOld"/&gt;
 *     &lt;enumeration value="MoveTerminate"/&gt;
 *     &lt;enumeration value="Migration"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OrderType")
@XmlEnum
public enum OrderType {

    @XmlEnumValue("Base")
    BASE("Base"),
    @XmlEnumValue("Access")
    ACCESS("Access"),
    @XmlEnumValue("Proposition")
    PROPOSITION("Proposition"),
    @XmlEnumValue("Change")
    CHANGE("Change"),
    @XmlEnumValue("Terminate")
    TERMINATE("Terminate"),
    @XmlEnumValue("Termination")
    TERMINATION("Termination"),
    @XmlEnumValue("Move")
    MOVE("Move"),
    @XmlEnumValue("MoveAccess")
    MOVE_ACCESS("MoveAccess"),
    @XmlEnumValue("MovePropositionNew")
    MOVE_PROPOSITION_NEW("MovePropositionNew"),
    @XmlEnumValue("MovePropositionOld")
    MOVE_PROPOSITION_OLD("MovePropositionOld"),
    @XmlEnumValue("MoveTerminate")
    MOVE_TERMINATE("MoveTerminate"),
    @XmlEnumValue("Migration")
    MIGRATION("Migration");
    private final String value;

    OrderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderType fromValue(String v) {
        for (OrderType c: OrderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
