//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Order"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="BaseOrder" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}BaseOrder"/&gt;
 *         &lt;element name="Quote" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}BaseOrder"/&gt;
 *         &lt;element name="FollowUpOrder" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}FollowUpOrder"/&gt;
 *         &lt;element name="MoveOrder" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}MoveOrder"/&gt;
 *         &lt;element name="TerminateOrder" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TerminateOrder"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order", propOrder = {
    "baseOrder",
    "quote",
    "followUpOrder",
    "moveOrder",
    "terminateOrder"
})
public class Order {

    @XmlElement(name = "BaseOrder")
    protected BaseOrder baseOrder;
    @XmlElement(name = "Quote")
    protected BaseOrder quote;
    @XmlElement(name = "FollowUpOrder")
    protected FollowUpOrder followUpOrder;
    @XmlElement(name = "MoveOrder")
    protected MoveOrder moveOrder;
    @XmlElement(name = "TerminateOrder")
    protected TerminateOrder terminateOrder;

    /**
     * Gets the value of the baseOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BaseOrder }
     *     
     */
    public BaseOrder getBaseOrder() {
        return baseOrder;
    }

    /**
     * Sets the value of the baseOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseOrder }
     *     
     */
    public void setBaseOrder(BaseOrder value) {
        this.baseOrder = value;
    }

    /**
     * Gets the value of the quote property.
     * 
     * @return
     *     possible object is
     *     {@link BaseOrder }
     *     
     */
    public BaseOrder getQuote() {
        return quote;
    }

    /**
     * Sets the value of the quote property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseOrder }
     *     
     */
    public void setQuote(BaseOrder value) {
        this.quote = value;
    }

    /**
     * Gets the value of the followUpOrder property.
     * 
     * @return
     *     possible object is
     *     {@link FollowUpOrder }
     *     
     */
    public FollowUpOrder getFollowUpOrder() {
        return followUpOrder;
    }

    /**
     * Sets the value of the followUpOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link FollowUpOrder }
     *     
     */
    public void setFollowUpOrder(FollowUpOrder value) {
        this.followUpOrder = value;
    }

    /**
     * Gets the value of the moveOrder property.
     * 
     * @return
     *     possible object is
     *     {@link MoveOrder }
     *     
     */
    public MoveOrder getMoveOrder() {
        return moveOrder;
    }

    /**
     * Sets the value of the moveOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoveOrder }
     *     
     */
    public void setMoveOrder(MoveOrder value) {
        this.moveOrder = value;
    }

    /**
     * Gets the value of the terminateOrder property.
     * 
     * @return
     *     possible object is
     *     {@link TerminateOrder }
     *     
     */
    public TerminateOrder getTerminateOrder() {
        return terminateOrder;
    }

    /**
     * Sets the value of the terminateOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminateOrder }
     *     
     */
    public void setTerminateOrder(TerminateOrder value) {
        this.terminateOrder = value;
    }

}
