//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Additional data needed"/&gt;
 *     &lt;enumeration value="Pending"/&gt;
 *     &lt;enumeration value="Wait"/&gt;
 *     &lt;enumeration value="CancellationInProgress"/&gt;
 *     &lt;enumeration value="Cancelled"/&gt;
 *     &lt;enumeration value="RejectionInProgress"/&gt;
 *     &lt;enumeration value="Rejected"/&gt;
 *     &lt;enumeration value="Open"/&gt;
 *     &lt;enumeration value="Started"/&gt;
 *     &lt;enumeration value="Planned"/&gt;
 *     &lt;enumeration value="Complete"/&gt;
 *     &lt;enumeration value="CancellationError"/&gt;
 *     &lt;enumeration value="TerminationError"/&gt;
 *     &lt;enumeration value="DeliveryError"/&gt;
 *     &lt;enumeration value="Pre-order"/&gt;
 *     &lt;enumeration value="Pre-subscribe"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OrderStatus")
@XmlEnum
public enum OrderStatus {

    @XmlEnumValue("Additional data needed")
    ADDITIONAL_DATA_NEEDED("Additional data needed"),
    @XmlEnumValue("Pending")
    PENDING("Pending"),
    @XmlEnumValue("Wait")
    WAIT("Wait"),
    @XmlEnumValue("CancellationInProgress")
    CANCELLATION_IN_PROGRESS("CancellationInProgress"),
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled"),
    @XmlEnumValue("RejectionInProgress")
    REJECTION_IN_PROGRESS("RejectionInProgress"),
    @XmlEnumValue("Rejected")
    REJECTED("Rejected"),
    @XmlEnumValue("Open")
    OPEN("Open"),
    @XmlEnumValue("Started")
    STARTED("Started"),
    @XmlEnumValue("Planned")
    PLANNED("Planned"),
    @XmlEnumValue("Complete")
    COMPLETE("Complete"),
    @XmlEnumValue("CancellationError")
    CANCELLATION_ERROR("CancellationError"),
    @XmlEnumValue("TerminationError")
    TERMINATION_ERROR("TerminationError"),
    @XmlEnumValue("DeliveryError")
    DELIVERY_ERROR("DeliveryError"),
    @XmlEnumValue("Pre-order")
    PRE_ORDER("Pre-order"),
    @XmlEnumValue("Pre-subscribe")
    PRE_SUBSCRIBE("Pre-subscribe");
    private final String value;

    OrderStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderStatus fromValue(String v) {
        for (OrderStatus c: OrderStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
