//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhoneNumberInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhoneNumberInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SubscriberInfo" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}PublicationCodes" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="NewPhoneNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NewPhoneNumber"/&gt;
 *           &lt;element name="PortingNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NumberPorting"/&gt;
 *           &lt;element name="ExistingNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ExistingNumber"/&gt;
 *           &lt;element name="CancelNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}CancelNumber"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneNumberInfo", propOrder = {
    "subscriberInfo",
    "newPhoneNumber",
    "portingNumber",
    "existingNumber",
    "cancelNumber"
})
public class PhoneNumberInfo {

    @XmlElement(name = "SubscriberInfo")
    @XmlSchemaType(name = "string")
    protected PublicationCodes subscriberInfo;
    @XmlElement(name = "NewPhoneNumber")
    protected NewPhoneNumber newPhoneNumber;
    @XmlElement(name = "PortingNumber")
    protected NumberPorting portingNumber;
    @XmlElement(name = "ExistingNumber")
    protected ExistingNumber existingNumber;
    @XmlElement(name = "CancelNumber")
    protected CancelNumber cancelNumber;

    /**
     * Gets the value of the subscriberInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationCodes }
     *     
     */
    public PublicationCodes getSubscriberInfo() {
        return subscriberInfo;
    }

    /**
     * Sets the value of the subscriberInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationCodes }
     *     
     */
    public void setSubscriberInfo(PublicationCodes value) {
        this.subscriberInfo = value;
    }

    /**
     * Gets the value of the newPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NewPhoneNumber }
     *     
     */
    public NewPhoneNumber getNewPhoneNumber() {
        return newPhoneNumber;
    }

    /**
     * Sets the value of the newPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewPhoneNumber }
     *     
     */
    public void setNewPhoneNumber(NewPhoneNumber value) {
        this.newPhoneNumber = value;
    }

    /**
     * Gets the value of the portingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NumberPorting }
     *     
     */
    public NumberPorting getPortingNumber() {
        return portingNumber;
    }

    /**
     * Sets the value of the portingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberPorting }
     *     
     */
    public void setPortingNumber(NumberPorting value) {
        this.portingNumber = value;
    }

    /**
     * Gets the value of the existingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ExistingNumber }
     *     
     */
    public ExistingNumber getExistingNumber() {
        return existingNumber;
    }

    /**
     * Sets the value of the existingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExistingNumber }
     *     
     */
    public void setExistingNumber(ExistingNumber value) {
        this.existingNumber = value;
    }

    /**
     * Gets the value of the cancelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CancelNumber }
     *     
     */
    public CancelNumber getCancelNumber() {
        return cancelNumber;
    }

    /**
     * Sets the value of the cancelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelNumber }
     *     
     */
    public void setCancelNumber(CancelNumber value) {
        this.cancelNumber = value;
    }

}
