//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrequalInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrequalInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IsraPointIdentification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FixedPhoneNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TelephoneNumber" minOccurs="0"/&gt;
 *         &lt;element name="ReferencePhoneNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TelephoneNumber" minOccurs="0"/&gt;
 *         &lt;element name="CurrentTelephonyType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TelephonyType" minOccurs="0"/&gt;
 *         &lt;element name="ReferenceXdfAccessServiceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="NoIsraPoint" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NoIsraPoint"/&gt;
 *           &lt;element name="MultipleIsraPoints" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}MultipleIsraPoints"/&gt;
 *           &lt;element name="NoServicesPresent" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}NoServicesPresent"/&gt;
 *           &lt;element name="ServicesPresent" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ServicesPresent"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrequalInfo", propOrder = {
    "israPointIdentification",
    "fixedPhoneNumber",
    "referencePhoneNumber",
    "currentTelephonyType",
    "referenceXdfAccessServiceId",
    "noIsraPoint",
    "multipleIsraPoints",
    "noServicesPresent",
    "servicesPresent"
})
public class PrequalInfo {

    @XmlElement(name = "IsraPointIdentification")
    protected String israPointIdentification;
    @XmlElement(name = "FixedPhoneNumber")
    protected String fixedPhoneNumber;
    @XmlElement(name = "ReferencePhoneNumber")
    protected String referencePhoneNumber;
    @XmlElement(name = "CurrentTelephonyType")
    @XmlSchemaType(name = "string")
    protected TelephonyType currentTelephonyType;
    @XmlElement(name = "ReferenceXdfAccessServiceId")
    protected String referenceXdfAccessServiceId;
    @XmlElement(name = "NoIsraPoint")
    protected NoIsraPoint noIsraPoint;
    @XmlElement(name = "MultipleIsraPoints")
    protected MultipleIsraPoints multipleIsraPoints;
    @XmlElement(name = "NoServicesPresent")
    protected NoServicesPresent noServicesPresent;
    @XmlElement(name = "ServicesPresent")
    protected ServicesPresent servicesPresent;

    /**
     * Gets the value of the israPointIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsraPointIdentification() {
        return israPointIdentification;
    }

    /**
     * Sets the value of the israPointIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsraPointIdentification(String value) {
        this.israPointIdentification = value;
    }

    /**
     * Gets the value of the fixedPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedPhoneNumber() {
        return fixedPhoneNumber;
    }

    /**
     * Sets the value of the fixedPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedPhoneNumber(String value) {
        this.fixedPhoneNumber = value;
    }

    /**
     * Gets the value of the referencePhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencePhoneNumber() {
        return referencePhoneNumber;
    }

    /**
     * Sets the value of the referencePhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencePhoneNumber(String value) {
        this.referencePhoneNumber = value;
    }

    /**
     * Gets the value of the currentTelephonyType property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonyType }
     *     
     */
    public TelephonyType getCurrentTelephonyType() {
        return currentTelephonyType;
    }

    /**
     * Sets the value of the currentTelephonyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonyType }
     *     
     */
    public void setCurrentTelephonyType(TelephonyType value) {
        this.currentTelephonyType = value;
    }

    /**
     * Gets the value of the referenceXdfAccessServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceXdfAccessServiceId() {
        return referenceXdfAccessServiceId;
    }

    /**
     * Sets the value of the referenceXdfAccessServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceXdfAccessServiceId(String value) {
        this.referenceXdfAccessServiceId = value;
    }

    /**
     * Gets the value of the noIsraPoint property.
     * 
     * @return
     *     possible object is
     *     {@link NoIsraPoint }
     *     
     */
    public NoIsraPoint getNoIsraPoint() {
        return noIsraPoint;
    }

    /**
     * Sets the value of the noIsraPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoIsraPoint }
     *     
     */
    public void setNoIsraPoint(NoIsraPoint value) {
        this.noIsraPoint = value;
    }

    /**
     * Gets the value of the multipleIsraPoints property.
     * 
     * @return
     *     possible object is
     *     {@link MultipleIsraPoints }
     *     
     */
    public MultipleIsraPoints getMultipleIsraPoints() {
        return multipleIsraPoints;
    }

    /**
     * Sets the value of the multipleIsraPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultipleIsraPoints }
     *     
     */
    public void setMultipleIsraPoints(MultipleIsraPoints value) {
        this.multipleIsraPoints = value;
    }

    /**
     * Gets the value of the noServicesPresent property.
     * 
     * @return
     *     possible object is
     *     {@link NoServicesPresent }
     *     
     */
    public NoServicesPresent getNoServicesPresent() {
        return noServicesPresent;
    }

    /**
     * Sets the value of the noServicesPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoServicesPresent }
     *     
     */
    public void setNoServicesPresent(NoServicesPresent value) {
        this.noServicesPresent = value;
    }

    /**
     * Gets the value of the servicesPresent property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesPresent }
     *     
     */
    public ServicesPresent getServicesPresent() {
        return servicesPresent;
    }

    /**
     * Sets the value of the servicesPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesPresent }
     *     
     */
    public void setServicesPresent(ServicesPresent value) {
        this.servicesPresent = value;
    }

}
