//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductCategory" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ProductCategory"/&gt;
 *         &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProductModel" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String32" minOccurs="0"/&gt;
 *         &lt;element name="ProductOneTimeCost" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price" minOccurs="0"/&gt;
 *         &lt;element name="ProductRecurringCost" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price" minOccurs="0"/&gt;
 *         &lt;element name="MaxQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Commercial" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Discount" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Orderable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OrderMethod" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}OrderMethod" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ArticleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveredProduct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Dependencies" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MonthlyAmountCheck" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}MonthlyAmountCheckLOV" minOccurs="0"/&gt;
 *         &lt;element name="TermsOfNoticeEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ContractStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "productId",
    "productName",
    "productCategory",
    "productType",
    "productModel",
    "productOneTimeCost",
    "productRecurringCost",
    "maxQuantity",
    "commercial",
    "discount",
    "visible",
    "orderable",
    "orderMethod",
    "articleCode",
    "deliveredProduct",
    "dependencies",
    "monthlyAmountCheck",
    "termsOfNoticeEndDate",
    "contractStartDate",
    "contractEndDate"
})
@XmlSeeAlso({
    InstalledBaseProduct.class
})
public class Product {

    @XmlElement(name = "ProductId", required = true)
    protected String productId;
    @XmlElement(name = "ProductName", required = true)
    protected String productName;
    @XmlElement(name = "ProductCategory", required = true)
    @XmlSchemaType(name = "string")
    protected ProductCategory productCategory;
    @XmlElement(name = "ProductType", required = true)
    protected String productType;
    @XmlElement(name = "ProductModel")
    protected String productModel;
    @XmlElement(name = "ProductOneTimeCost")
    protected BigDecimal productOneTimeCost;
    @XmlElement(name = "ProductRecurringCost")
    protected BigDecimal productRecurringCost;
    @XmlElement(name = "MaxQuantity")
    protected Integer maxQuantity;
    @XmlElement(name = "Commercial")
    protected boolean commercial;
    @XmlElement(name = "Discount")
    protected boolean discount;
    @XmlElement(name = "Visible")
    protected boolean visible;
    @XmlElement(name = "Orderable")
    protected Boolean orderable;
    @XmlElement(name = "OrderMethod")
    @XmlSchemaType(name = "string")
    protected List<OrderMethod> orderMethod;
    @XmlElement(name = "ArticleCode")
    protected String articleCode;
    @XmlElement(name = "DeliveredProduct")
    protected String deliveredProduct;
    @XmlElement(name = "Dependencies")
    protected String dependencies;
    @XmlElement(name = "MonthlyAmountCheck")
    @XmlSchemaType(name = "string")
    protected MonthlyAmountCheckLOV monthlyAmountCheck;
    @XmlElement(name = "TermsOfNoticeEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar termsOfNoticeEndDate;
    @XmlElement(name = "ContractStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractStartDate;
    @XmlElement(name = "ContractEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractEndDate;

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategory }
     *     
     */
    public ProductCategory getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategory }
     *     
     */
    public void setProductCategory(ProductCategory value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * Sets the value of the productModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductModel(String value) {
        this.productModel = value;
    }

    /**
     * Gets the value of the productOneTimeCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductOneTimeCost() {
        return productOneTimeCost;
    }

    /**
     * Sets the value of the productOneTimeCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductOneTimeCost(BigDecimal value) {
        this.productOneTimeCost = value;
    }

    /**
     * Gets the value of the productRecurringCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProductRecurringCost() {
        return productRecurringCost;
    }

    /**
     * Sets the value of the productRecurringCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProductRecurringCost(BigDecimal value) {
        this.productRecurringCost = value;
    }

    /**
     * Gets the value of the maxQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxQuantity() {
        return maxQuantity;
    }

    /**
     * Sets the value of the maxQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxQuantity(Integer value) {
        this.maxQuantity = value;
    }

    /**
     * Gets the value of the commercial property.
     * 
     */
    public boolean isCommercial() {
        return commercial;
    }

    /**
     * Sets the value of the commercial property.
     * 
     */
    public void setCommercial(boolean value) {
        this.commercial = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     */
    public boolean isDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(boolean value) {
        this.discount = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     */
    public boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     */
    public void setVisible(boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the orderable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOrderable() {
        return orderable;
    }

    /**
     * Sets the value of the orderable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrderable(Boolean value) {
        this.orderable = value;
    }

    /**
     * Gets the value of the orderMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderMethod }
     * 
     * 
     */
    public List<OrderMethod> getOrderMethod() {
        if (orderMethod == null) {
            orderMethod = new ArrayList<OrderMethod>();
        }
        return this.orderMethod;
    }

    /**
     * Gets the value of the articleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleCode() {
        return articleCode;
    }

    /**
     * Sets the value of the articleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleCode(String value) {
        this.articleCode = value;
    }

    /**
     * Gets the value of the deliveredProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveredProduct() {
        return deliveredProduct;
    }

    /**
     * Sets the value of the deliveredProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveredProduct(String value) {
        this.deliveredProduct = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependencies(String value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the monthlyAmountCheck property.
     * 
     * @return
     *     possible object is
     *     {@link MonthlyAmountCheckLOV }
     *     
     */
    public MonthlyAmountCheckLOV getMonthlyAmountCheck() {
        return monthlyAmountCheck;
    }

    /**
     * Sets the value of the monthlyAmountCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthlyAmountCheckLOV }
     *     
     */
    public void setMonthlyAmountCheck(MonthlyAmountCheckLOV value) {
        this.monthlyAmountCheck = value;
    }

    /**
     * Gets the value of the termsOfNoticeEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTermsOfNoticeEndDate() {
        return termsOfNoticeEndDate;
    }

    /**
     * Sets the value of the termsOfNoticeEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTermsOfNoticeEndDate(XMLGregorianCalendar value) {
        this.termsOfNoticeEndDate = value;
    }

    /**
     * Gets the value of the contractStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractStartDate() {
        return contractStartDate;
    }

    /**
     * Sets the value of the contractStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractStartDate(XMLGregorianCalendar value) {
        this.contractStartDate = value;
    }

    /**
     * Gets the value of the contractEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractEndDate() {
        return contractEndDate;
    }

    /**
     * Sets the value of the contractEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractEndDate(XMLGregorianCalendar value) {
        this.contractEndDate = value;
    }

}
