//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuoteStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QuoteStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Wait"/&gt;
 *     &lt;enumeration value="Rejected"/&gt;
 *     &lt;enumeration value="Cancelled"/&gt;
 *     &lt;enumeration value="WaitForBulkSubmit"/&gt;
 *     &lt;enumeration value="FailedBulkOrder"/&gt;
 *     &lt;enumeration value="ForceWait"/&gt;
 *     &lt;enumeration value="ForceThruBulkSubmit"/&gt;
 *     &lt;enumeration value="BulkOrderDelivered"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QuoteStatus")
@XmlEnum
public enum QuoteStatus {

    @XmlEnumValue("Wait")
    WAIT("Wait"),
    @XmlEnumValue("Rejected")
    REJECTED("Rejected"),
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled"),
    @XmlEnumValue("WaitForBulkSubmit")
    WAIT_FOR_BULK_SUBMIT("WaitForBulkSubmit"),
    @XmlEnumValue("FailedBulkOrder")
    FAILED_BULK_ORDER("FailedBulkOrder"),
    @XmlEnumValue("ForceWait")
    FORCE_WAIT("ForceWait"),
    @XmlEnumValue("ForceThruBulkSubmit")
    FORCE_THRU_BULK_SUBMIT("ForceThruBulkSubmit"),
    @XmlEnumValue("BulkOrderDelivered")
    BULK_ORDER_DELIVERED("BulkOrderDelivered");
    private final String value;

    QuoteStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QuoteStatus fromValue(String v) {
        for (QuoteStatus c: QuoteStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
