//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServicesPresent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServicesPresent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OwnedByCustomer" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ServicesOwnedByCustomer" minOccurs="0"/&gt;
 *         &lt;element name="NotOwnedByCustomer" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ServicesNotOwnedByCustomer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServicesPresent", propOrder = {
    "phoneLineOwned",
    "migratePhoneLine",
    "ownedByCustomer",
    "notOwnedByCustomer"
})
public class ServicesPresent {

    @XmlElement(name = "PhoneLineOwned")
    protected Boolean phoneLineOwned;
    @XmlElement(name = "MigratePhoneLine")
    protected Boolean migratePhoneLine;
    @XmlElement(name = "OwnedByCustomer")
    protected ServicesOwnedByCustomer ownedByCustomer;
    @XmlElement(name = "NotOwnedByCustomer")
    protected ServicesNotOwnedByCustomer notOwnedByCustomer;

    /**
     * Gets the value of the phoneLineOwned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPhoneLineOwned() {
        return phoneLineOwned;
    }

    /**
     * Sets the value of the phoneLineOwned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPhoneLineOwned(Boolean value) {
        this.phoneLineOwned = value;
    }

    /**
     * Gets the value of the migratePhoneLine property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMigratePhoneLine() {
        return migratePhoneLine;
    }

    /**
     * Sets the value of the migratePhoneLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMigratePhoneLine(Boolean value) {
        this.migratePhoneLine = value;
    }

    /**
     * Gets the value of the ownedByCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesOwnedByCustomer }
     *     
     */
    public ServicesOwnedByCustomer getOwnedByCustomer() {
        return ownedByCustomer;
    }

    /**
     * Sets the value of the ownedByCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesOwnedByCustomer }
     *     
     */
    public void setOwnedByCustomer(ServicesOwnedByCustomer value) {
        this.ownedByCustomer = value;
    }

    /**
     * Gets the value of the notOwnedByCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesNotOwnedByCustomer }
     *     
     */
    public ServicesNotOwnedByCustomer getNotOwnedByCustomer() {
        return notOwnedByCustomer;
    }

    /**
     * Sets the value of the notOwnedByCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesNotOwnedByCustomer }
     *     
     */
    public void setNotOwnedByCustomer(ServicesNotOwnedByCustomer value) {
        this.notOwnedByCustomer = value;
    }

}
