//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuspendInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuspendInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountSubstatus" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}AccountSubstatus"/&gt;
 *         &lt;element name="SuspendReason" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}SuspendReason"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuspendInfo", propOrder = {
    "accountSubstatus",
    "suspendReason"
})
public class SuspendInfo {

    @XmlElement(name = "AccountSubstatus", required = true)
    protected String accountSubstatus;
    @XmlElement(name = "SuspendReason", required = true)
    @XmlSchemaType(name = "string")
    protected SuspendReason suspendReason;

    /**
     * Gets the value of the accountSubstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountSubstatus() {
        return accountSubstatus;
    }

    /**
     * Sets the value of the accountSubstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountSubstatus(String value) {
        this.accountSubstatus = value;
    }

    /**
     * Gets the value of the suspendReason property.
     * 
     * @return
     *     possible object is
     *     {@link SuspendReason }
     *     
     */
    public SuspendReason getSuspendReason() {
        return suspendReason;
    }

    /**
     * Sets the value of the suspendReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuspendReason }
     *     
     */
    public void setSuspendReason(SuspendReason value) {
        this.suspendReason = value;
    }

}
