//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Totals complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Totals"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TotalRecurringCost" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price"/&gt;
 *         &lt;element name="TotalOneTimeCost" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}Price"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Totals", propOrder = {
    "totalRecurringCost",
    "totalOneTimeCost"
})
public class Totals {

    @XmlElement(name = "TotalRecurringCost", required = true)
    protected BigDecimal totalRecurringCost;
    @XmlElement(name = "TotalOneTimeCost", required = true)
    protected BigDecimal totalOneTimeCost;

    /**
     * Gets the value of the totalRecurringCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalRecurringCost() {
        return totalRecurringCost;
    }

    /**
     * Sets the value of the totalRecurringCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalRecurringCost(BigDecimal value) {
        this.totalRecurringCost = value;
    }

    /**
     * Gets the value of the totalOneTimeCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalOneTimeCost() {
        return totalOneTimeCost;
    }

    /**
     * Sets the value of the totalOneTimeCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalOneTimeCost(BigDecimal value) {
        this.totalOneTimeCost = value;
    }

}
