//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tvProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tvProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rcProfileId" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" minOccurs="0"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="hdChannelCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sdChannelCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="technologyType" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String20" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tvProfile", propOrder = {
    "rcProfileId",
    "priority",
    "hdChannelCount",
    "sdChannelCount",
    "technologyType"
})
public class TvProfile {

    protected String rcProfileId;
    protected int priority;
    protected int hdChannelCount;
    protected int sdChannelCount;
    @XmlElement(required = true)
    protected List<String> technologyType;

    /**
     * Gets the value of the rcProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcProfileId() {
        return rcProfileId;
    }

    /**
     * Sets the value of the rcProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcProfileId(String value) {
        this.rcProfileId = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the hdChannelCount property.
     * 
     */
    public int getHdChannelCount() {
        return hdChannelCount;
    }

    /**
     * Sets the value of the hdChannelCount property.
     * 
     */
    public void setHdChannelCount(int value) {
        this.hdChannelCount = value;
    }

    /**
     * Gets the value of the sdChannelCount property.
     * 
     */
    public int getSdChannelCount() {
        return sdChannelCount;
    }

    /**
     * Sets the value of the sdChannelCount property.
     * 
     */
    public void setSdChannelCount(int value) {
        this.sdChannelCount = value;
    }

    /**
     * Gets the value of the technologyType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technologyType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnologyType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTechnologyType() {
        if (technologyType == null) {
            technologyType = new ArrayList<String>();
        }
        return this.technologyType;
    }

}
