//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:05 PM IST 
//


package com.intershop.cordysServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VoiceService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoiceService"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:fiber.kpn.com:crm:frontdesk:data:v0}ServiceSpec"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PhoneNumber" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}TelephoneNumber"/&gt;
 *         &lt;element name="Telco" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}String255" minOccurs="0"/&gt;
 *         &lt;element name="BNumberMaskFlag" type="{urn:fiber.kpn.com:crm:frontdesk:data:v0}BNumberMaskFlag" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoiceService", propOrder = {
    "phoneNumber",
    "telco",
    "bNumberMaskFlag"
})
public class VoiceService
    extends ServiceSpec
{

    @XmlElement(name = "PhoneNumber", required = true)
    protected String phoneNumber;
    @XmlElement(name = "Telco")
    protected String telco;
    @XmlElement(name = "BNumberMaskFlag")
    @XmlSchemaType(name = "string")
    protected BNumberMaskFlag bNumberMaskFlag;

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the telco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelco() {
        return telco;
    }

    /**
     * Sets the value of the telco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelco(String value) {
        this.telco = value;
    }

    /**
     * Gets the value of the bNumberMaskFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BNumberMaskFlag }
     *     
     */
    public BNumberMaskFlag getBNumberMaskFlag() {
        return bNumberMaskFlag;
    }

    /**
     * Sets the value of the bNumberMaskFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BNumberMaskFlag }
     *     
     */
    public void setBNumberMaskFlag(BNumberMaskFlag value) {
        this.bNumberMaskFlag = value;
    }

}
