//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:13 PM IST 
//


package com.intershop.pegaServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HardWareStatusRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HardWareStatusRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fpIdEquipmentManagement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IAServiceIdfpIdLocationAccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NTArticleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentCarrierTechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TargetCarrierTechnologyType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FTU-Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CurrentPromotion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TargetPromotion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HardWareStatusRequestType", propOrder = {
    "fpIdEquipmentManagement",
    "iaServiceIdfpIdLocationAccess",
    "ntArticleCode",
    "currentCarrierTechnologyType",
    "targetCarrierTechnologyType",
    "ftuType",
    "orderType",
    "currentPromotion",
    "targetPromotion"
})
public class HardWareStatusRequestType {

    protected String fpIdEquipmentManagement;
    @XmlElement(name = "IAServiceIdfpIdLocationAccess")
    protected String iaServiceIdfpIdLocationAccess;
    @XmlElement(name = "NTArticleCode")
    protected String ntArticleCode;
    @XmlElement(name = "CurrentCarrierTechnologyType")
    protected String currentCarrierTechnologyType;
    @XmlElement(name = "TargetCarrierTechnologyType", required = true)
    protected String targetCarrierTechnologyType;
    @XmlElement(name = "FTU-Type")
    protected String ftuType;
    @XmlElement(name = "OrderType", required = true)
    protected String orderType;
    @XmlElement(name = "CurrentPromotion", required = true)
    protected String currentPromotion;
    @XmlElement(name = "TargetPromotion", required = true)
    protected String targetPromotion;

    /**
     * Gets the value of the fpIdEquipmentManagement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpIdEquipmentManagement() {
        return fpIdEquipmentManagement;
    }

    /**
     * Sets the value of the fpIdEquipmentManagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpIdEquipmentManagement(String value) {
        this.fpIdEquipmentManagement = value;
    }

    /**
     * Gets the value of the iaServiceIdfpIdLocationAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIAServiceIdfpIdLocationAccess() {
        return iaServiceIdfpIdLocationAccess;
    }

    /**
     * Sets the value of the iaServiceIdfpIdLocationAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIAServiceIdfpIdLocationAccess(String value) {
        this.iaServiceIdfpIdLocationAccess = value;
    }

    /**
     * Gets the value of the ntArticleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNTArticleCode() {
        return ntArticleCode;
    }

    /**
     * Sets the value of the ntArticleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNTArticleCode(String value) {
        this.ntArticleCode = value;
    }

    /**
     * Gets the value of the currentCarrierTechnologyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentCarrierTechnologyType() {
        return currentCarrierTechnologyType;
    }

    /**
     * Sets the value of the currentCarrierTechnologyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentCarrierTechnologyType(String value) {
        this.currentCarrierTechnologyType = value;
    }

    /**
     * Gets the value of the targetCarrierTechnologyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetCarrierTechnologyType() {
        return targetCarrierTechnologyType;
    }

    /**
     * Sets the value of the targetCarrierTechnologyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetCarrierTechnologyType(String value) {
        this.targetCarrierTechnologyType = value;
    }

    /**
     * Gets the value of the ftuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTUType() {
        return ftuType;
    }

    /**
     * Sets the value of the ftuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTUType(String value) {
        this.ftuType = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the currentPromotion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentPromotion() {
        return currentPromotion;
    }

    /**
     * Sets the value of the currentPromotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentPromotion(String value) {
        this.currentPromotion = value;
    }

    /**
     * Gets the value of the targetPromotion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetPromotion() {
        return targetPromotion;
    }

    /**
     * Sets the value of the targetPromotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetPromotion(String value) {
        this.targetPromotion = value;
    }

}
