//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 01:29:13 PM IST 
//


package com.intershop.pegaServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessQuoteToOrderResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessQuoteToOrderResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="QuoteHeader"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="QuoteRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ProcessingMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="QuoteBody"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ReasonText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessQuoteToOrderResponseType", propOrder = {
    "quoteHeader",
    "quoteBody"
})
public class ProcessQuoteToOrderResponseType {

    @XmlElement(name = "QuoteHeader", required = true)
    protected ProcessQuoteToOrderResponseType.QuoteHeader quoteHeader;
    @XmlElement(name = "QuoteBody", required = true)
    protected ProcessQuoteToOrderResponseType.QuoteBody quoteBody;

    /**
     * Gets the value of the quoteHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessQuoteToOrderResponseType.QuoteHeader }
     *     
     */
    public ProcessQuoteToOrderResponseType.QuoteHeader getQuoteHeader() {
        return quoteHeader;
    }

    /**
     * Sets the value of the quoteHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessQuoteToOrderResponseType.QuoteHeader }
     *     
     */
    public void setQuoteHeader(ProcessQuoteToOrderResponseType.QuoteHeader value) {
        this.quoteHeader = value;
    }

    /**
     * Gets the value of the quoteBody property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessQuoteToOrderResponseType.QuoteBody }
     *     
     */
    public ProcessQuoteToOrderResponseType.QuoteBody getQuoteBody() {
        return quoteBody;
    }

    /**
     * Sets the value of the quoteBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessQuoteToOrderResponseType.QuoteBody }
     *     
     */
    public void setQuoteBody(ProcessQuoteToOrderResponseType.QuoteBody value) {
        this.quoteBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ReasonText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reasonCode",
        "reasonText"
    })
    public static class QuoteBody {

        @XmlElement(name = "ReasonCode", required = true)
        protected String reasonCode;
        @XmlElement(name = "ReasonText", required = true)
        protected String reasonText;

        /**
         * Gets the value of the reasonCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReasonCode() {
            return reasonCode;
        }

        /**
         * Sets the value of the reasonCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReasonCode(String value) {
            this.reasonCode = value;
        }

        /**
         * Gets the value of the reasonText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReasonText() {
            return reasonText;
        }

        /**
         * Sets the value of the reasonText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReasonText(String value) {
            this.reasonText = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="QuoteRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ProcessingMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quoteRefId",
        "processingMode",
        "orderType"
    })
    public static class QuoteHeader {

        @XmlElement(name = "QuoteRefId", required = true)
        protected String quoteRefId;
        @XmlElement(name = "ProcessingMode", required = true)
        protected String processingMode;
        @XmlElement(name = "OrderType", required = true)
        protected String orderType;

        /**
         * Gets the value of the quoteRefId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuoteRefId() {
            return quoteRefId;
        }

        /**
         * Sets the value of the quoteRefId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuoteRefId(String value) {
            this.quoteRefId = value;
        }

        /**
         * Gets the value of the processingMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessingMode() {
            return processingMode;
        }

        /**
         * Sets the value of the processingMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessingMode(String value) {
            this.processingMode = value;
        }

        /**
         * Gets the value of the orderType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderType() {
            return orderType;
        }

        /**
         * Sets the value of the orderType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderType(String value) {
            this.orderType = value;
        }

    }

}
