package com.intershop.model;

/**
 * Created by bhati502 on 11-5-2017.
 */
public enum Services {
    GETCUSTOMERINFORMATION,
    GETINSTALLEDBASE,
    SAVEORDER,
    VASAVAILABILITY,
    PACKAGEAVAILABILITY,
    GETFIRSTPOSSIBLEWISHDATE,
    SIMPLEPREQUALIFY,
    VALIDATETELEPHONENUMBER,
    SEARCHCUSTOMER,
    GETINITIALORDERCUSTOEMRDETAILS,
    GETINITIALORDEREMAILVALIDATION,
    GETINITIALORDERTELEPHONEVALIDATION,
    GETINITIALORDERSAVEORDERDETAILS,
    ACCESSORDERSECENARIO,
    HARDWARESTATUS,
    GETAVAILABLEPLANDATES,
    CHECKPENDINGORDERS,
    UPDATEPRIVACY;

}
