//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.28 at 02:32:19 PM IST 
//


package com.intershop.accessOrderService;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AOSDeterminationResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AOSDeterminationResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Response" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ResultCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AccessOrderScenario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ServicePresent" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AlertIDList" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="AlertID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="PrequalInfo" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ISRAPointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="FixedPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ReferenceXdfAccessServiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ReferencePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CurrentPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="NoISRAPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MultipleISRAPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="BroadbandPresent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CustomerAnswers" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="NumberofNI1Lines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="NumberofNI2Lines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MultipleServicesMultipleLines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="NL-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="FTU-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="TandL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AgentActivity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AgentActivityReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="TargetCarrierTechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="HDChannels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SDChannels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Upload" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Download" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RCProfileID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RemoveTechnologyTypes" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="TechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AccessInstallation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AskRemoveTelephony" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LineSharing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AOSDeterminationResponseType", propOrder = {
    "response"
})
public class AOSDeterminationResponseType {

    @XmlElement(name = "Response")
    protected AOSDeterminationResponseType.Response response;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link AOSDeterminationResponseType.Response }
     *     
     */
    public AOSDeterminationResponseType.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link AOSDeterminationResponseType.Response }
     *     
     */
    public void setResponse(AOSDeterminationResponseType.Response value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ResultCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AccessOrderScenario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ServicePresent" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AlertIDList" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="AlertID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="PrequalInfo" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ISRAPointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="FixedPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ReferenceXdfAccessServiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ReferencePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CurrentPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="NoISRAPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MultipleISRAPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="BroadbandPresent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CustomerAnswers" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="NumberofNI1Lines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="NumberofNI2Lines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MultipleServicesMultipleLines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="NL-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="FTU-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="TandL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AgentActivity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AgentActivityReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="TargetCarrierTechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="HDChannels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SDChannels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Upload" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Download" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RCProfileID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RemoveTechnologyTypes" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="TechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AccessInstallation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AskRemoveTelephony" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LineSharing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resultCode",
        "resultCodeDescription",
        "accessOrderScenario",
        "servicePresent",
        "alertIDList",
        "prequalInfo",
        "nlType",
        "ftuType",
        "tandL",
        "agentActivity",
        "agentActivityReason",
        "targetCarrierTechnologyType",
        "hdChannels",
        "sdChannels",
        "upload",
        "download",
        "rcProfileID",
        "removeTechnologyTypes",
        "accessInstallation",
        "askRemoveTelephony",
        "lineSharing"
    })
    public static class Response {

        @XmlElement(name = "ResultCode")
        protected String resultCode;
        @XmlElement(name = "ResultCodeDescription")
        protected String resultCodeDescription;
        @XmlElement(name = "AccessOrderScenario", required = true)
        protected String accessOrderScenario;
        @XmlElement(name = "ServicePresent")
        protected AOSDeterminationResponseType.Response.ServicePresent servicePresent;
        @XmlElement(name = "AlertIDList")
        protected AOSDeterminationResponseType.Response.AlertIDList alertIDList;
        @XmlElement(name = "PrequalInfo")
        protected AOSDeterminationResponseType.Response.PrequalInfo prequalInfo;
        @XmlElement(name = "NL-type")
        protected String nlType;
        @XmlElement(name = "FTU-type")
        protected String ftuType;
        @XmlElement(name = "TandL")
        protected String tandL;
        @XmlElement(name = "AgentActivity")
        protected String agentActivity;
        @XmlElement(name = "AgentActivityReason")
        protected String agentActivityReason;
        @XmlElement(name = "TargetCarrierTechnologyType")
        protected String targetCarrierTechnologyType;
        @XmlElement(name = "HDChannels")
        protected String hdChannels;
        @XmlElement(name = "SDChannels")
        protected String sdChannels;
        @XmlElement(name = "Upload")
        protected String upload;
        @XmlElement(name = "Download")
        protected String download;
        @XmlElement(name = "RCProfileID")
        protected String rcProfileID;
        @XmlElement(name = "RemoveTechnologyTypes")
        protected AOSDeterminationResponseType.Response.RemoveTechnologyTypes removeTechnologyTypes;
        @XmlElement(name = "AccessInstallation")
        protected String accessInstallation;
        @XmlElement(name = "AskRemoveTelephony")
        protected String askRemoveTelephony;
        @XmlElement(name = "LineSharing")
        protected String lineSharing;

        /**
         * Gets the value of the resultCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultCode() {
            return resultCode;
        }

        /**
         * Sets the value of the resultCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultCode(String value) {
            this.resultCode = value;
        }

        /**
         * Gets the value of the resultCodeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultCodeDescription() {
            return resultCodeDescription;
        }

        /**
         * Sets the value of the resultCodeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultCodeDescription(String value) {
            this.resultCodeDescription = value;
        }

        /**
         * Gets the value of the accessOrderScenario property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessOrderScenario() {
            return accessOrderScenario;
        }

        /**
         * Sets the value of the accessOrderScenario property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessOrderScenario(String value) {
            this.accessOrderScenario = value;
        }

        /**
         * Gets the value of the servicePresent property.
         * 
         * @return
         *     possible object is
         *     {@link AOSDeterminationResponseType.Response.ServicePresent }
         *     
         */
        public AOSDeterminationResponseType.Response.ServicePresent getServicePresent() {
            return servicePresent;
        }

        /**
         * Sets the value of the servicePresent property.
         * 
         * @param value
         *     allowed object is
         *     {@link AOSDeterminationResponseType.Response.ServicePresent }
         *     
         */
        public void setServicePresent(AOSDeterminationResponseType.Response.ServicePresent value) {
            this.servicePresent = value;
        }

        /**
         * Gets the value of the alertIDList property.
         * 
         * @return
         *     possible object is
         *     {@link AOSDeterminationResponseType.Response.AlertIDList }
         *     
         */
        public AOSDeterminationResponseType.Response.AlertIDList getAlertIDList() {
            return alertIDList;
        }

        /**
         * Sets the value of the alertIDList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AOSDeterminationResponseType.Response.AlertIDList }
         *     
         */
        public void setAlertIDList(AOSDeterminationResponseType.Response.AlertIDList value) {
            this.alertIDList = value;
        }

        /**
         * Gets the value of the prequalInfo property.
         * 
         * @return
         *     possible object is
         *     {@link AOSDeterminationResponseType.Response.PrequalInfo }
         *     
         */
        public AOSDeterminationResponseType.Response.PrequalInfo getPrequalInfo() {
            return prequalInfo;
        }

        /**
         * Sets the value of the prequalInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link AOSDeterminationResponseType.Response.PrequalInfo }
         *     
         */
        public void setPrequalInfo(AOSDeterminationResponseType.Response.PrequalInfo value) {
            this.prequalInfo = value;
        }

        /**
         * Gets the value of the nlType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNLType() {
            return nlType;
        }

        /**
         * Sets the value of the nlType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNLType(String value) {
            this.nlType = value;
        }

        /**
         * Gets the value of the ftuType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFTUType() {
            return ftuType;
        }

        /**
         * Sets the value of the ftuType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFTUType(String value) {
            this.ftuType = value;
        }

        /**
         * Gets the value of the tandL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTandL() {
            return tandL;
        }

        /**
         * Sets the value of the tandL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTandL(String value) {
            this.tandL = value;
        }

        /**
         * Gets the value of the agentActivity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgentActivity() {
            return agentActivity;
        }

        /**
         * Sets the value of the agentActivity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgentActivity(String value) {
            this.agentActivity = value;
        }

        /**
         * Gets the value of the agentActivityReason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgentActivityReason() {
            return agentActivityReason;
        }

        /**
         * Sets the value of the agentActivityReason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgentActivityReason(String value) {
            this.agentActivityReason = value;
        }

        /**
         * Gets the value of the targetCarrierTechnologyType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetCarrierTechnologyType() {
            return targetCarrierTechnologyType;
        }

        /**
         * Sets the value of the targetCarrierTechnologyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetCarrierTechnologyType(String value) {
            this.targetCarrierTechnologyType = value;
        }

        /**
         * Gets the value of the hdChannels property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHDChannels() {
            return hdChannels;
        }

        /**
         * Sets the value of the hdChannels property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHDChannels(String value) {
            this.hdChannels = value;
        }

        /**
         * Gets the value of the sdChannels property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSDChannels() {
            return sdChannels;
        }

        /**
         * Sets the value of the sdChannels property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSDChannels(String value) {
            this.sdChannels = value;
        }

        /**
         * Gets the value of the upload property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUpload() {
            return upload;
        }

        /**
         * Sets the value of the upload property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUpload(String value) {
            this.upload = value;
        }

        /**
         * Gets the value of the download property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDownload() {
            return download;
        }

        /**
         * Sets the value of the download property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDownload(String value) {
            this.download = value;
        }

        /**
         * Gets the value of the rcProfileID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRCProfileID() {
            return rcProfileID;
        }

        /**
         * Sets the value of the rcProfileID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRCProfileID(String value) {
            this.rcProfileID = value;
        }

        /**
         * Gets the value of the removeTechnologyTypes property.
         * 
         * @return
         *     possible object is
         *     {@link AOSDeterminationResponseType.Response.RemoveTechnologyTypes }
         *     
         */
        public AOSDeterminationResponseType.Response.RemoveTechnologyTypes getRemoveTechnologyTypes() {
            return removeTechnologyTypes;
        }

        /**
         * Sets the value of the removeTechnologyTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link AOSDeterminationResponseType.Response.RemoveTechnologyTypes }
         *     
         */
        public void setRemoveTechnologyTypes(AOSDeterminationResponseType.Response.RemoveTechnologyTypes value) {
            this.removeTechnologyTypes = value;
        }

        /**
         * Gets the value of the accessInstallation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessInstallation() {
            return accessInstallation;
        }

        /**
         * Sets the value of the accessInstallation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessInstallation(String value) {
            this.accessInstallation = value;
        }

        /**
         * Gets the value of the askRemoveTelephony property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAskRemoveTelephony() {
            return askRemoveTelephony;
        }

        /**
         * Sets the value of the askRemoveTelephony property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAskRemoveTelephony(String value) {
            this.askRemoveTelephony = value;
        }

        /**
         * Gets the value of the lineSharing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLineSharing() {
            return lineSharing;
        }

        /**
         * Sets the value of the lineSharing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLineSharing(String value) {
            this.lineSharing = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="AlertID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alertID"
        })
        public static class AlertIDList {

            @XmlElement(name = "AlertID")
            protected List<String> alertID;

            /**
             * Gets the value of the alertID property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the alertID property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAlertID().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAlertID() {
                if (alertID == null) {
                    alertID = new ArrayList<String>();
                }
                return this.alertID;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ISRAPointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="FixedPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ReferenceXdfAccessServiceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ReferencePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CurrentPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="NoISRAPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MultipleISRAPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="BroadbandPresent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CustomerAnswers" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="NumberofNI1Lines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="NumberofNI2Lines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MultipleServicesMultipleLines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "israPointID",
            "fixedPhoneNumber",
            "referenceXdfAccessServiceID",
            "referencePhoneNumber",
            "currentPhoneType",
            "noISRAPoint",
            "multipleISRAPoint",
            "broadbandPresent",
            "customerAnswers",
            "numberofNI1Lines",
            "numberofNI2Lines",
            "multipleServicesMultipleLines"
        })
        public static class PrequalInfo {

            @XmlElement(name = "ISRAPointID")
            protected String israPointID;
            @XmlElement(name = "FixedPhoneNumber")
            protected String fixedPhoneNumber;
            @XmlElement(name = "ReferenceXdfAccessServiceID")
            protected String referenceXdfAccessServiceID;
            @XmlElement(name = "ReferencePhoneNumber")
            protected String referencePhoneNumber;
            @XmlElement(name = "CurrentPhoneType")
            protected String currentPhoneType;
            @XmlElement(name = "NoISRAPoint")
            protected String noISRAPoint;
            @XmlElement(name = "MultipleISRAPoint")
            protected String multipleISRAPoint;
            @XmlElement(name = "BroadbandPresent")
            protected String broadbandPresent;
            @XmlElement(name = "CustomerAnswers")
            protected AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers customerAnswers;
            @XmlElement(name = "NumberofNI1Lines")
            protected String numberofNI1Lines;
            @XmlElement(name = "NumberofNI2Lines")
            protected String numberofNI2Lines;
            @XmlElement(name = "MultipleServicesMultipleLines")
            protected String multipleServicesMultipleLines;

            /**
             * Gets the value of the israPointID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getISRAPointID() {
                return israPointID;
            }

            /**
             * Sets the value of the israPointID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setISRAPointID(String value) {
                this.israPointID = value;
            }

            /**
             * Gets the value of the fixedPhoneNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFixedPhoneNumber() {
                return fixedPhoneNumber;
            }

            /**
             * Sets the value of the fixedPhoneNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFixedPhoneNumber(String value) {
                this.fixedPhoneNumber = value;
            }

            /**
             * Gets the value of the referenceXdfAccessServiceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferenceXdfAccessServiceID() {
                return referenceXdfAccessServiceID;
            }

            /**
             * Sets the value of the referenceXdfAccessServiceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferenceXdfAccessServiceID(String value) {
                this.referenceXdfAccessServiceID = value;
            }

            /**
             * Gets the value of the referencePhoneNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReferencePhoneNumber() {
                return referencePhoneNumber;
            }

            /**
             * Sets the value of the referencePhoneNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReferencePhoneNumber(String value) {
                this.referencePhoneNumber = value;
            }

            /**
             * Gets the value of the currentPhoneType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrentPhoneType() {
                return currentPhoneType;
            }

            /**
             * Sets the value of the currentPhoneType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrentPhoneType(String value) {
                this.currentPhoneType = value;
            }

            /**
             * Gets the value of the noISRAPoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoISRAPoint() {
                return noISRAPoint;
            }

            /**
             * Sets the value of the noISRAPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoISRAPoint(String value) {
                this.noISRAPoint = value;
            }

            /**
             * Gets the value of the multipleISRAPoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMultipleISRAPoint() {
                return multipleISRAPoint;
            }

            /**
             * Sets the value of the multipleISRAPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMultipleISRAPoint(String value) {
                this.multipleISRAPoint = value;
            }

            /**
             * Gets the value of the broadbandPresent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBroadbandPresent() {
                return broadbandPresent;
            }

            /**
             * Sets the value of the broadbandPresent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBroadbandPresent(String value) {
                this.broadbandPresent = value;
            }

            /**
             * Gets the value of the customerAnswers property.
             * 
             * @return
             *     possible object is
             *     {@link AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers }
             *     
             */
            public AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers getCustomerAnswers() {
                return customerAnswers;
            }

            /**
             * Sets the value of the customerAnswers property.
             * 
             * @param value
             *     allowed object is
             *     {@link AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers }
             *     
             */
            public void setCustomerAnswers(AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers value) {
                this.customerAnswers = value;
            }

            /**
             * Gets the value of the numberofNI1Lines property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumberofNI1Lines() {
                return numberofNI1Lines;
            }

            /**
             * Sets the value of the numberofNI1Lines property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumberofNI1Lines(String value) {
                this.numberofNI1Lines = value;
            }

            /**
             * Gets the value of the numberofNI2Lines property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumberofNI2Lines() {
                return numberofNI2Lines;
            }

            /**
             * Sets the value of the numberofNI2Lines property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumberofNI2Lines(String value) {
                this.numberofNI2Lines = value;
            }

            /**
             * Gets the value of the multipleServicesMultipleLines property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMultipleServicesMultipleLines() {
                return multipleServicesMultipleLines;
            }

            /**
             * Sets the value of the multipleServicesMultipleLines property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMultipleServicesMultipleLines(String value) {
                this.multipleServicesMultipleLines = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "phoneLineOwned",
                "broadbandOwned",
                "migratePhoneLine",
                "migrateBroadband",
                "soleResident"
            })
            public static class CustomerAnswers {

                @XmlElement(name = "PhoneLineOwned")
                protected String phoneLineOwned;
                @XmlElement(name = "BroadbandOwned")
                protected String broadbandOwned;
                @XmlElement(name = "MigratePhoneLine")
                protected String migratePhoneLine;
                @XmlElement(name = "MigrateBroadband")
                protected String migrateBroadband;
                @XmlElement(name = "SoleResident")
                protected String soleResident;

                /**
                 * Gets the value of the phoneLineOwned property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPhoneLineOwned() {
                    return phoneLineOwned;
                }

                /**
                 * Sets the value of the phoneLineOwned property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPhoneLineOwned(String value) {
                    this.phoneLineOwned = value;
                }

                /**
                 * Gets the value of the broadbandOwned property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBroadbandOwned() {
                    return broadbandOwned;
                }

                /**
                 * Sets the value of the broadbandOwned property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBroadbandOwned(String value) {
                    this.broadbandOwned = value;
                }

                /**
                 * Gets the value of the migratePhoneLine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMigratePhoneLine() {
                    return migratePhoneLine;
                }

                /**
                 * Sets the value of the migratePhoneLine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMigratePhoneLine(String value) {
                    this.migratePhoneLine = value;
                }

                /**
                 * Gets the value of the migrateBroadband property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMigrateBroadband() {
                    return migrateBroadband;
                }

                /**
                 * Sets the value of the migrateBroadband property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMigrateBroadband(String value) {
                    this.migrateBroadband = value;
                }

                /**
                 * Gets the value of the soleResident property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSoleResident() {
                    return soleResident;
                }

                /**
                 * Sets the value of the soleResident property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSoleResident(String value) {
                    this.soleResident = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="TechnologyType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "technologyType"
        })
        public static class RemoveTechnologyTypes {

            @XmlElement(name = "TechnologyType", required = true)
            protected List<String> technologyType;

            /**
             * Gets the value of the technologyType property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the technologyType property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTechnologyType().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getTechnologyType() {
                if (technologyType == null) {
                    technologyType = new ArrayList<String>();
                }
                return this.technologyType;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="PhoneLineOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="BroadbandOwned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MigratePhoneLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MigrateBroadband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="SoleResident" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "phoneLineOwned",
            "broadbandOwned",
            "migratePhoneLine",
            "migrateBroadband",
            "soleResident"
        })
        public static class ServicePresent {

            @XmlElement(name = "PhoneLineOwned")
            protected String phoneLineOwned;
            @XmlElement(name = "BroadbandOwned")
            protected String broadbandOwned;
            @XmlElement(name = "MigratePhoneLine")
            protected String migratePhoneLine;
            @XmlElement(name = "MigrateBroadband")
            protected String migrateBroadband;
            @XmlElement(name = "SoleResident")
            protected String soleResident;

            /**
             * Gets the value of the phoneLineOwned property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhoneLineOwned() {
                return phoneLineOwned;
            }

            /**
             * Sets the value of the phoneLineOwned property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhoneLineOwned(String value) {
                this.phoneLineOwned = value;
            }

            /**
             * Gets the value of the broadbandOwned property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBroadbandOwned() {
                return broadbandOwned;
            }

            /**
             * Sets the value of the broadbandOwned property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBroadbandOwned(String value) {
                this.broadbandOwned = value;
            }

            /**
             * Gets the value of the migratePhoneLine property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMigratePhoneLine() {
                return migratePhoneLine;
            }

            /**
             * Sets the value of the migratePhoneLine property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMigratePhoneLine(String value) {
                this.migratePhoneLine = value;
            }

            /**
             * Gets the value of the migrateBroadband property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMigrateBroadband() {
                return migrateBroadband;
            }

            /**
             * Sets the value of the migrateBroadband property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMigrateBroadband(String value) {
                this.migrateBroadband = value;
            }

            /**
             * Gets the value of the soleResident property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSoleResident() {
                return soleResident;
            }

            /**
             * Sets the value of the soleResident property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSoleResident(String value) {
                this.soleResident = value;
            }

        }

    }

}
