//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.28 at 02:32:19 PM IST 
//


package com.intershop.accessOrderService;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intershop.accessOrderService package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AOSDeterminationRequest_QNAME = new QName("AOSDeterminationAndTechnology", "AOSDeterminationRequest");
    private final static QName _AOSDeterminationResponse_QNAME = new QName("AOSDeterminationAndTechnology", "AOSDeterminationResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intershop.accessOrderService
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType }
     * 
     */
    public AOSDeterminationResponseType createAOSDeterminationResponseType() {
        return new AOSDeterminationResponseType();
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType.Response }
     * 
     */
    public AOSDeterminationResponseType.Response createAOSDeterminationResponseTypeResponse() {
        return new AOSDeterminationResponseType.Response();
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType.Response.PrequalInfo }
     * 
     */
    public AOSDeterminationResponseType.Response.PrequalInfo createAOSDeterminationResponseTypeResponsePrequalInfo() {
        return new AOSDeterminationResponseType.Response.PrequalInfo();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType }
     * 
     */
    public AOSDeterminationRequestType createAOSDeterminationRequestType() {
        return new AOSDeterminationRequestType();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request }
     * 
     */
    public AOSDeterminationRequestType.Request createAOSDeterminationRequestTypeRequest() {
        return new AOSDeterminationRequestType.Request();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TechCapabilities }
     * 
     */
    public AOSDeterminationRequestType.Request.TechCapabilities createAOSDeterminationRequestTypeRequestTechCapabilities() {
        return new AOSDeterminationRequestType.Request.TechCapabilities();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TargetPromotion }
     * 
     */
    public AOSDeterminationRequestType.Request.TargetPromotion createAOSDeterminationRequestTypeRequestTargetPromotion() {
        return new AOSDeterminationRequestType.Request.TargetPromotion();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TargetPromotion.ProductList }
     * 
     */
    public AOSDeterminationRequestType.Request.TargetPromotion.ProductList createAOSDeterminationRequestTypeRequestTargetPromotionProductList() {
        return new AOSDeterminationRequestType.Request.TargetPromotion.ProductList();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TargetPromotion.CarrierTechTypes }
     * 
     */
    public AOSDeterminationRequestType.Request.TargetPromotion.CarrierTechTypes createAOSDeterminationRequestTypeRequestTargetPromotionCarrierTechTypes() {
        return new AOSDeterminationRequestType.Request.TargetPromotion.CarrierTechTypes();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.CurrentPromotion }
     * 
     */
    public AOSDeterminationRequestType.Request.CurrentPromotion createAOSDeterminationRequestTypeRequestCurrentPromotion() {
        return new AOSDeterminationRequestType.Request.CurrentPromotion();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.CurrentPromotion.CarrierTechTypes }
     * 
     */
    public AOSDeterminationRequestType.Request.CurrentPromotion.CarrierTechTypes createAOSDeterminationRequestTypeRequestCurrentPromotionCarrierTechTypes() {
        return new AOSDeterminationRequestType.Request.CurrentPromotion.CarrierTechTypes();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.PrequalInfo }
     * 
     */
    public AOSDeterminationRequestType.Request.PrequalInfo createAOSDeterminationRequestTypeRequestPrequalInfo() {
        return new AOSDeterminationRequestType.Request.PrequalInfo();
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType.Response.ServicePresent }
     * 
     */
    public AOSDeterminationResponseType.Response.ServicePresent createAOSDeterminationResponseTypeResponseServicePresent() {
        return new AOSDeterminationResponseType.Response.ServicePresent();
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType.Response.AlertIDList }
     * 
     */
    public AOSDeterminationResponseType.Response.AlertIDList createAOSDeterminationResponseTypeResponseAlertIDList() {
        return new AOSDeterminationResponseType.Response.AlertIDList();
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType.Response.RemoveTechnologyTypes }
     * 
     */
    public AOSDeterminationResponseType.Response.RemoveTechnologyTypes createAOSDeterminationResponseTypeResponseRemoveTechnologyTypes() {
        return new AOSDeterminationResponseType.Response.RemoveTechnologyTypes();
    }

    /**
     * Create an instance of {@link AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers }
     * 
     */
    public AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers createAOSDeterminationResponseTypeResponsePrequalInfoCustomerAnswers() {
        return new AOSDeterminationResponseType.Response.PrequalInfo.CustomerAnswers();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.Address }
     * 
     */
    public AOSDeterminationRequestType.Request.Address createAOSDeterminationRequestTypeRequestAddress() {
        return new AOSDeterminationRequestType.Request.Address();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.PortingPhoneNumberList }
     * 
     */
    public AOSDeterminationRequestType.Request.PortingPhoneNumberList createAOSDeterminationRequestTypeRequestPortingPhoneNumberList() {
        return new AOSDeterminationRequestType.Request.PortingPhoneNumberList();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TechCapabilities.TechCapability }
     * 
     */
    public AOSDeterminationRequestType.Request.TechCapabilities.TechCapability createAOSDeterminationRequestTypeRequestTechCapabilitiesTechCapability() {
        return new AOSDeterminationRequestType.Request.TechCapabilities.TechCapability();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TargetPromotion.ProductList.Product }
     * 
     */
    public AOSDeterminationRequestType.Request.TargetPromotion.ProductList.Product createAOSDeterminationRequestTypeRequestTargetPromotionProductListProduct() {
        return new AOSDeterminationRequestType.Request.TargetPromotion.ProductList.Product();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.TargetPromotion.CarrierTechTypes.TVProfile }
     * 
     */
    public AOSDeterminationRequestType.Request.TargetPromotion.CarrierTechTypes.TVProfile createAOSDeterminationRequestTypeRequestTargetPromotionCarrierTechTypesTVProfile() {
        return new AOSDeterminationRequestType.Request.TargetPromotion.CarrierTechTypes.TVProfile();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.CurrentPromotion.CarrierTechTypes.TVProfile }
     * 
     */
    public AOSDeterminationRequestType.Request.CurrentPromotion.CarrierTechTypes.TVProfile createAOSDeterminationRequestTypeRequestCurrentPromotionCarrierTechTypesTVProfile() {
        return new AOSDeterminationRequestType.Request.CurrentPromotion.CarrierTechTypes.TVProfile();
    }

    /**
     * Create an instance of {@link AOSDeterminationRequestType.Request.PrequalInfo.CustomerAnswers }
     * 
     */
    public AOSDeterminationRequestType.Request.PrequalInfo.CustomerAnswers createAOSDeterminationRequestTypeRequestPrequalInfoCustomerAnswers() {
        return new AOSDeterminationRequestType.Request.PrequalInfo.CustomerAnswers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AOSDeterminationRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AOSDeterminationAndTechnology", name = "AOSDeterminationRequest")
    public JAXBElement<AOSDeterminationRequestType> createAOSDeterminationRequest(AOSDeterminationRequestType value) {
        return new JAXBElement<AOSDeterminationRequestType>(_AOSDeterminationRequest_QNAME, AOSDeterminationRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AOSDeterminationResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AOSDeterminationAndTechnology", name = "AOSDeterminationResponse")
    public JAXBElement<AOSDeterminationResponseType> createAOSDeterminationResponse(AOSDeterminationResponseType value) {
        return new JAXBElement<AOSDeterminationResponseType>(_AOSDeterminationResponse_QNAME, AOSDeterminationResponseType.class, null, value);
    }

}
